// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/ip_transport.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IpAddrFamily: IP Address family
type IpAddrFamily int32

const (
	// undefined ip version
	IpAddrFamily_IPV_UNDEF IpAddrFamily = 0
	// IPv4
	IpAddrFamily_IPV4 IpAddrFamily = 1
	// IPv6
	IpAddrFamily_IPV6 IpAddrFamily = 2
)

// Enum value maps for IpAddrFamily.
var (
	IpAddrFamily_name = map[int32]string{
		0: "IPV_UNDEF",
		1: "IPV4",
		2: "IPV6",
	}
	IpAddrFamily_value = map[string]int32{
		"IPV_UNDEF": 0,
		"IPV4":      1,
		"IPV6":      2,
	}
)

func (x IpAddrFamily) Enum() *IpAddrFamily {
	p := new(IpAddrFamily)
	*p = x
	return p
}

func (x IpAddrFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpAddrFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_common_ip_transport_proto_enumTypes[0].Descriptor()
}

func (IpAddrFamily) Type() protoreflect.EnumType {
	return &file_common_ip_transport_proto_enumTypes[0]
}

func (x IpAddrFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpAddrFamily.Descriptor instead.
func (IpAddrFamily) EnumDescriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0}
}

// Ingress / Egress traffic dir
type Traffic int32

const (
	// undefined traffic direction
	Traffic_DIR_UNDEF Traffic = 0
	// Ingress
	Traffic_INGRESS Traffic = 1
	// Egress
	Traffic_EGRESS Traffic = 2
)

// Enum value maps for Traffic.
var (
	Traffic_name = map[int32]string{
		0: "DIR_UNDEF",
		1: "INGRESS",
		2: "EGRESS",
	}
	Traffic_value = map[string]int32{
		"DIR_UNDEF": 0,
		"INGRESS":   1,
		"EGRESS":    2,
	}
)

func (x Traffic) Enum() *Traffic {
	p := new(Traffic)
	*p = x
	return p
}

func (x Traffic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Traffic) Descriptor() protoreflect.EnumDescriptor {
	return file_common_ip_transport_proto_enumTypes[1].Descriptor()
}

func (Traffic) Type() protoreflect.EnumType {
	return &file_common_ip_transport_proto_enumTypes[1]
}

func (x Traffic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Traffic.Descriptor instead.
func (Traffic) EnumDescriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{1}
}

// Transport: represents net transport (L4)
type Networks_NetIP_Transport int32

const (
	// TCP
	Networks_NetIP_TCP Networks_NetIP_Transport = 0
	// UDP
	Networks_NetIP_UDP Networks_NetIP_Transport = 1
)

// Enum value maps for Networks_NetIP_Transport.
var (
	Networks_NetIP_Transport_name = map[int32]string{
		0: "TCP",
		1: "UDP",
	}
	Networks_NetIP_Transport_value = map[string]int32{
		"TCP": 0,
		"UDP": 1,
	}
)

func (x Networks_NetIP_Transport) Enum() *Networks_NetIP_Transport {
	p := new(Networks_NetIP_Transport)
	*p = x
	return p
}

func (x Networks_NetIP_Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Networks_NetIP_Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_common_ip_transport_proto_enumTypes[2].Descriptor()
}

func (Networks_NetIP_Transport) Type() protoreflect.EnumType {
	return &file_common_ip_transport_proto_enumTypes[2]
}

func (x Networks_NetIP_Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Networks_NetIP_Transport.Descriptor instead.
func (Networks_NetIP_Transport) EnumDescriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0, 0, 0}
}

// Networks: represents network types
type Networks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Networks) Reset() {
	*x = Networks{}
	mi := &file_common_ip_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Networks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Networks) ProtoMessage() {}

func (x *Networks) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Networks.ProtoReflect.Descriptor instead.
func (*Networks) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0}
}

// IP/ICMP protocol
type ICMP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP address family
	Ipv IpAddrFamily `protobuf:"varint,1,opt,name=ipv,proto3,enum=common.IpAddrFamily" json:"ipv,omitempty"`
	// ICMP message types
	Types         []uint32 `protobuf:"varint,2,rep,packed,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICMP) Reset() {
	*x = ICMP{}
	mi := &file_common_ip_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICMP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICMP) ProtoMessage() {}

func (x *ICMP) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICMP.ProtoReflect.Descriptor instead.
func (*ICMP) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{1}
}

func (x *ICMP) GetIpv() IpAddrFamily {
	if x != nil {
		return x.Ipv
	}
	return IpAddrFamily_IPV_UNDEF
}

func (x *ICMP) GetTypes() []uint32 {
	if x != nil {
		return x.Types
	}
	return nil
}

// IPs: represents list of IP addresses
type IPs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ipv4: list of IPv4 addresses
	Ipv4 []string `protobuf:"bytes,1,rep,name=ipv4,json=IPv4,proto3" json:"ipv4,omitempty"`
	// Ipv6: list of IPv6 addresses
	Ipv6          []string `protobuf:"bytes,2,rep,name=ipv6,json=IPv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPs) Reset() {
	*x = IPs{}
	mi := &file_common_ip_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPs) ProtoMessage() {}

func (x *IPs) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPs.ProtoReflect.Descriptor instead.
func (*IPs) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{2}
}

func (x *IPs) GetIpv4() []string {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *IPs) GetIpv6() []string {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

// NetIP: represents IP-Network type (L3)
type Networks_NetIP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CIDR: IP range
	Cidr          string `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Networks_NetIP) Reset() {
	*x = Networks_NetIP{}
	mi := &file_common_ip_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Networks_NetIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Networks_NetIP) ProtoMessage() {}

func (x *Networks_NetIP) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Networks_NetIP.ProtoReflect.Descriptor instead.
func (*Networks_NetIP) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Networks_NetIP) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

// PortRange: port [from - to] range
type Networks_NetIP_PortRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// From: range left bound
	From uint32 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	// To: range right bound
	To            uint32 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Networks_NetIP_PortRange) Reset() {
	*x = Networks_NetIP_PortRange{}
	mi := &file_common_ip_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Networks_NetIP_PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Networks_NetIP_PortRange) ProtoMessage() {}

func (x *Networks_NetIP_PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Networks_NetIP_PortRange.ProtoReflect.Descriptor instead.
func (*Networks_NetIP_PortRange) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Networks_NetIP_PortRange) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Networks_NetIP_PortRange) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

var File_common_ip_transport_proto protoreflect.FileDescriptor

const file_common_ip_transport_proto_rawDesc = "" +
	"\n" +
	"\x19common/ip_transport.proto\x12\x06common\"w\n" +
	"\bNetworks\x1ak\n" +
	"\x05NetIP\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x1a/\n" +
	"\tPortRange\x12\x12\n" +
	"\x04from\x18\x01 \x01(\rR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\rR\x02to\"\x1d\n" +
	"\tTransport\x12\a\n" +
	"\x03TCP\x10\x00\x12\a\n" +
	"\x03UDP\x10\x01\"D\n" +
	"\x04ICMP\x12&\n" +
	"\x03ipv\x18\x01 \x01(\x0e2\x14.common.IpAddrFamilyR\x03ipv\x12\x14\n" +
	"\x05types\x18\x02 \x03(\rR\x05types\"-\n" +
	"\x03IPs\x12\x12\n" +
	"\x04ipv4\x18\x01 \x03(\tR\x04IPv4\x12\x12\n" +
	"\x04ipv6\x18\x02 \x03(\tR\x04IPv6*1\n" +
	"\fIpAddrFamily\x12\r\n" +
	"\tIPV_UNDEF\x10\x00\x12\b\n" +
	"\x04IPV4\x10\x01\x12\b\n" +
	"\x04IPV6\x10\x02*1\n" +
	"\aTraffic\x12\r\n" +
	"\tDIR_UNDEF\x10\x00\x12\v\n" +
	"\aINGRESS\x10\x01\x12\n" +
	"\n" +
	"\x06EGRESS\x10\x02B=Z;github.com/PRO-Robotech/sgroups-proto/pkg/api/common;commonb\x06proto3"

var (
	file_common_ip_transport_proto_rawDescOnce sync.Once
	file_common_ip_transport_proto_rawDescData []byte
)

func file_common_ip_transport_proto_rawDescGZIP() []byte {
	file_common_ip_transport_proto_rawDescOnce.Do(func() {
		file_common_ip_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_ip_transport_proto_rawDesc), len(file_common_ip_transport_proto_rawDesc)))
	})
	return file_common_ip_transport_proto_rawDescData
}

var file_common_ip_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_ip_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_ip_transport_proto_goTypes = []any{
	(IpAddrFamily)(0),                // 0: common.IpAddrFamily
	(Traffic)(0),                     // 1: common.Traffic
	(Networks_NetIP_Transport)(0),    // 2: common.Networks.NetIP.Transport
	(*Networks)(nil),                 // 3: common.Networks
	(*ICMP)(nil),                     // 4: common.ICMP
	(*IPs)(nil),                      // 5: common.IPs
	(*Networks_NetIP)(nil),           // 6: common.Networks.NetIP
	(*Networks_NetIP_PortRange)(nil), // 7: common.Networks.NetIP.PortRange
}
var file_common_ip_transport_proto_depIdxs = []int32{
	0, // 0: common.ICMP.ipv:type_name -> common.IpAddrFamily
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_ip_transport_proto_init() }
func file_common_ip_transport_proto_init() {
	if File_common_ip_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_ip_transport_proto_rawDesc), len(file_common_ip_transport_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_ip_transport_proto_goTypes,
		DependencyIndexes: file_common_ip_transport_proto_depIdxs,
		EnumInfos:         file_common_ip_transport_proto_enumTypes,
		MessageInfos:      file_common_ip_transport_proto_msgTypes,
	}.Build()
	File_common_ip_transport_proto = out.File
	file_common_ip_transport_proto_goTypes = nil
	file_common_ip_transport_proto_depIdxs = nil
}
