// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/resource.proto

package common

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action: enumeration of possible actions
type Action int32

const (
	// UNKNOWN: unknown action
	Action_UNKNOWN Action = 0
	// ALLOW: allow action
	Action_ALLOW Action = 1
	// DENY: deny action
	Action_DENY Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "UNKNOWN",
		1: "ALLOW",
		2: "DENY",
	}
	Action_value = map[string]int32{
		"UNKNOWN": 0,
		"ALLOW":   1,
		"DENY":    2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_common_resource_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_common_resource_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{0}
}

// Metadata: common resource metadata
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UID: unique identifier. Use this for update requests; for create requests, leave it empty
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Name: resource name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace: resource namespace
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Labels: resource labels
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Annotations: resource annotations
	Annotations map[string]string `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// CreationTimestamp: resource creation timestamp
	CreationTimestamp string `protobuf:"bytes,6,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	// RevisionVersion: resource revision version
	RevisionVersion string `protobuf:"bytes,7,opt,name=revision_version,json=revisionVersion,proto3" json:"revision_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_common_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Metadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Metadata) GetCreationTimestamp() string {
	if x != nil {
		return x.CreationTimestamp
	}
	return ""
}

func (x *Metadata) GetRevisionVersion() string {
	if x != nil {
		return x.RevisionVersion
	}
	return ""
}

// MetadataScope: common resource metadata for scoping
type MetadataScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UID: unique identifier. Use this for update requests; for create requests, leave it empty
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Name: resource name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace: resource namespace
	Namespace     string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataScope) Reset() {
	*x = MetadataScope{}
	mi := &file_common_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataScope) ProtoMessage() {}

func (x *MetadataScope) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataScope.ProtoReflect.Descriptor instead.
func (*MetadataScope) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataScope) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *MetadataScope) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataScope) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// ResSelector: resource selector
type ResSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FieldSelector: field selector
	FieldSelector *ResSelector_FieldSelector `protobuf:"bytes,1,opt,name=field_selector,json=fieldSelector,proto3" json:"field_selector,omitempty"`
	// LabelSelector: label selector
	LabelSelector map[string]string `protobuf:"bytes,2,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResSelector) Reset() {
	*x = ResSelector{}
	mi := &file_common_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResSelector) ProtoMessage() {}

func (x *ResSelector) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResSelector.ProtoReflect.Descriptor instead.
func (*ResSelector) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{2}
}

func (x *ResSelector) GetFieldSelector() *ResSelector_FieldSelector {
	if x != nil {
		return x.FieldSelector
	}
	return nil
}

func (x *ResSelector) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

// FieldSelector: resource field selector
type ResSelector_FieldSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name: resource name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace: resource namespace
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Refs: resource references
	Refs          []*ResSelector_FieldSelector_ResourceRef `protobuf:"bytes,3,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResSelector_FieldSelector) Reset() {
	*x = ResSelector_FieldSelector{}
	mi := &file_common_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResSelector_FieldSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResSelector_FieldSelector) ProtoMessage() {}

func (x *ResSelector_FieldSelector) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResSelector_FieldSelector.ProtoReflect.Descriptor instead.
func (*ResSelector_FieldSelector) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ResSelector_FieldSelector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResSelector_FieldSelector) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResSelector_FieldSelector) GetRefs() []*ResSelector_FieldSelector_ResourceRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

// ResourceRef: reference to a resource
type ResSelector_FieldSelector_ResourceRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name: reference resource name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace: reference resource namespace
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// ResType: reference resource type
	ResType       string `protobuf:"bytes,3,opt,name=res_type,json=resType,proto3" json:"res_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResSelector_FieldSelector_ResourceRef) Reset() {
	*x = ResSelector_FieldSelector_ResourceRef{}
	mi := &file_common_resource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResSelector_FieldSelector_ResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResSelector_FieldSelector_ResourceRef) ProtoMessage() {}

func (x *ResSelector_FieldSelector_ResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResSelector_FieldSelector_ResourceRef.ProtoReflect.Descriptor instead.
func (*ResSelector_FieldSelector_ResourceRef) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ResSelector_FieldSelector_ResourceRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResSelector_FieldSelector_ResourceRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResSelector_FieldSelector_ResourceRef) GetResType() string {
	if x != nil {
		return x.ResType
	}
	return ""
}

var File_common_resource_proto protoreflect.FileDescriptor

const file_common_resource_proto_rawDesc = "" +
	"\n" +
	"\x15common/resource.proto\x12\x06common\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xf2\x05\n" +
	"\bMetadata\x12\xea\x01\n" +
	"\x03uid\x18\x01 \x01(\tB\xd7\x01\x92A\xd3\x01*\x03uid2Uid of the resource. Use this for update requests; for create requests, leave it emptyJ&\"2438ac3c-37eb-4902-adef-ed16b4431030\"\x8a\x01E^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$\xa2\x02\x04uuidR\x03uid\x12>\n" +
	"\x04name\x18\x02 \x01(\tB*\xbaH'\xd8\x01\x01r\"\x10\x01\x18\xfd\x012\x1b^[a-z0-9][a-z0-9.-]{0,252}$R\x04name\x12U\n" +
	"\tnamespace\x18\x03 \x01(\tB7\xe0A\x01\xbaH1\xd8\x01\x01r,\x10\x01\x18?2&^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$R\tnamespace\x124\n" +
	"\x06labels\x18\x04 \x03(\v2\x1c.common.Metadata.LabelsEntryR\x06labels\x12C\n" +
	"\vannotations\x18\x05 \x03(\v2!.common.Metadata.AnnotationsEntryR\vannotations\x127\n" +
	"\x12creation_timestamp\x18\x06 \x01(\tB\b\x92A\x02@\x01\xe0A\x03R\x11creationTimestamp\x123\n" +
	"\x10revision_version\x18\a \x01(\tB\b\x92A\x02@\x01\xe0A\x03R\x0frevisionVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\rMetadataScope\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"\xcb\x03\n" +
	"\vResSelector\x12H\n" +
	"\x0efield_selector\x18\x01 \x01(\v2!.common.ResSelector.FieldSelectorR\rfieldSelector\x12M\n" +
	"\x0elabel_selector\x18\x02 \x03(\v2&.common.ResSelector.LabelSelectorEntryR\rlabelSelector\x1a\xe0\x01\n" +
	"\rFieldSelector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12A\n" +
	"\x04refs\x18\x03 \x03(\v2-.common.ResSelector.FieldSelector.ResourceRefR\x04refs\x1aZ\n" +
	"\vResourceRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x19\n" +
	"\bres_type\x18\x03 \x01(\tR\aresType\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01**\n" +
	"\x06Action\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\x12\b\n" +
	"\x04DENY\x10\x02B=Z;github.com/PRO-Robotech/sgroups-proto/pkg/api/common;commonb\x06proto3"

var (
	file_common_resource_proto_rawDescOnce sync.Once
	file_common_resource_proto_rawDescData []byte
)

func file_common_resource_proto_rawDescGZIP() []byte {
	file_common_resource_proto_rawDescOnce.Do(func() {
		file_common_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_resource_proto_rawDesc), len(file_common_resource_proto_rawDesc)))
	})
	return file_common_resource_proto_rawDescData
}

var file_common_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_common_resource_proto_goTypes = []any{
	(Action)(0),                       // 0: common.Action
	(*Metadata)(nil),                  // 1: common.Metadata
	(*MetadataScope)(nil),             // 2: common.MetadataScope
	(*ResSelector)(nil),               // 3: common.ResSelector
	nil,                               // 4: common.Metadata.LabelsEntry
	nil,                               // 5: common.Metadata.AnnotationsEntry
	(*ResSelector_FieldSelector)(nil), // 6: common.ResSelector.FieldSelector
	nil,                               // 7: common.ResSelector.LabelSelectorEntry
	(*ResSelector_FieldSelector_ResourceRef)(nil), // 8: common.ResSelector.FieldSelector.ResourceRef
}
var file_common_resource_proto_depIdxs = []int32{
	4, // 0: common.Metadata.labels:type_name -> common.Metadata.LabelsEntry
	5, // 1: common.Metadata.annotations:type_name -> common.Metadata.AnnotationsEntry
	6, // 2: common.ResSelector.field_selector:type_name -> common.ResSelector.FieldSelector
	7, // 3: common.ResSelector.label_selector:type_name -> common.ResSelector.LabelSelectorEntry
	8, // 4: common.ResSelector.FieldSelector.refs:type_name -> common.ResSelector.FieldSelector.ResourceRef
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_resource_proto_init() }
func file_common_resource_proto_init() {
	if File_common_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_resource_proto_rawDesc), len(file_common_resource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_resource_proto_goTypes,
		DependencyIndexes: file_common_resource_proto_depIdxs,
		EnumInfos:         file_common_resource_proto_enumTypes,
		MessageInfos:      file_common_resource_proto_msgTypes,
	}.Build()
	File_common_resource_proto = out.File
	file_common_resource_proto_goTypes = nil
	file_common_resource_proto_depIdxs = nil
}
