// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sgroups/v1/queries.proto

package sgroupsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NamespaceReq: namespace requests
type NamespaceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceReq) Reset() {
	*x = NamespaceReq{}
	mi := &file_sgroups_v1_queries_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceReq) ProtoMessage() {}

func (x *NamespaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_queries_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceReq.ProtoReflect.Descriptor instead.
func (*NamespaceReq) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_queries_proto_rawDescGZIP(), []int{0}
}

// Selector: resource selector
type NamespaceReq_Selector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// field_selector: field selector
	FieldSelector *NamespaceReq_Selector_FieldSelector `protobuf:"bytes,1,opt,name=field_selector,json=fieldSelector,proto3" json:"field_selector,omitempty"`
	// label_selector: label selector
	LabelSelector map[string]string `protobuf:"bytes,2,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceReq_Selector) Reset() {
	*x = NamespaceReq_Selector{}
	mi := &file_sgroups_v1_queries_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceReq_Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceReq_Selector) ProtoMessage() {}

func (x *NamespaceReq_Selector) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_queries_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceReq_Selector.ProtoReflect.Descriptor instead.
func (*NamespaceReq_Selector) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_queries_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NamespaceReq_Selector) GetFieldSelector() *NamespaceReq_Selector_FieldSelector {
	if x != nil {
		return x.FieldSelector
	}
	return nil
}

func (x *NamespaceReq_Selector) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

// Upsert: request to upsert namespaces
type NamespaceReq_Upsert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespaces: list of namespaces
	Namespaces    []*Namespace `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceReq_Upsert) Reset() {
	*x = NamespaceReq_Upsert{}
	mi := &file_sgroups_v1_queries_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceReq_Upsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceReq_Upsert) ProtoMessage() {}

func (x *NamespaceReq_Upsert) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_queries_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceReq_Upsert.ProtoReflect.Descriptor instead.
func (*NamespaceReq_Upsert) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_queries_proto_rawDescGZIP(), []int{0, 1}
}

func (x *NamespaceReq_Upsert) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

// Delete: request to delete namespaces
type NamespaceReq_Delete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespaces: list of namespaces to delete
	Namespaces    []*NamespaceReq_Delete_Namespace `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceReq_Delete) Reset() {
	*x = NamespaceReq_Delete{}
	mi := &file_sgroups_v1_queries_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceReq_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceReq_Delete) ProtoMessage() {}

func (x *NamespaceReq_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_queries_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceReq_Delete.ProtoReflect.Descriptor instead.
func (*NamespaceReq_Delete) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_queries_proto_rawDescGZIP(), []int{0, 2}
}

func (x *NamespaceReq_Delete) GetNamespaces() []*NamespaceReq_Delete_Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

// List: request to list namespaces
type NamespaceReq_List struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// selectors: list of selectors
	Selectors     []*NamespaceReq_Selector `protobuf:"bytes,1,rep,name=selectors,proto3" json:"selectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceReq_List) Reset() {
	*x = NamespaceReq_List{}
	mi := &file_sgroups_v1_queries_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceReq_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceReq_List) ProtoMessage() {}

func (x *NamespaceReq_List) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_queries_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceReq_List.ProtoReflect.Descriptor instead.
func (*NamespaceReq_List) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_queries_proto_rawDescGZIP(), []int{0, 3}
}

func (x *NamespaceReq_List) GetSelectors() []*NamespaceReq_Selector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

// Watch: request to watch namespaces
type NamespaceReq_Watch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// selectors: list of selectors
	Selectors     []*NamespaceReq_Selector `protobuf:"bytes,1,rep,name=selectors,proto3" json:"selectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceReq_Watch) Reset() {
	*x = NamespaceReq_Watch{}
	mi := &file_sgroups_v1_queries_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceReq_Watch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceReq_Watch) ProtoMessage() {}

func (x *NamespaceReq_Watch) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_queries_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceReq_Watch.ProtoReflect.Descriptor instead.
func (*NamespaceReq_Watch) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_queries_proto_rawDescGZIP(), []int{0, 4}
}

func (x *NamespaceReq_Watch) GetSelectors() []*NamespaceReq_Selector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

// FieldSelector: resource field selector
type NamespaceReq_Selector_FieldSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name: resource name
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceReq_Selector_FieldSelector) Reset() {
	*x = NamespaceReq_Selector_FieldSelector{}
	mi := &file_sgroups_v1_queries_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceReq_Selector_FieldSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceReq_Selector_FieldSelector) ProtoMessage() {}

func (x *NamespaceReq_Selector_FieldSelector) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_queries_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceReq_Selector_FieldSelector.ProtoReflect.Descriptor instead.
func (*NamespaceReq_Selector_FieldSelector) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_queries_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *NamespaceReq_Selector_FieldSelector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// MetadataScope: namespace metadata for scoping
type NamespaceReq_Delete_MetadataScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scoped: scope by uid or name
	//
	// Types that are valid to be assigned to Scoped:
	//
	//	*NamespaceReq_Delete_MetadataScope_Uid
	//	*NamespaceReq_Delete_MetadataScope_Name
	Scoped        isNamespaceReq_Delete_MetadataScope_Scoped `protobuf_oneof:"scoped"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceReq_Delete_MetadataScope) Reset() {
	*x = NamespaceReq_Delete_MetadataScope{}
	mi := &file_sgroups_v1_queries_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceReq_Delete_MetadataScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceReq_Delete_MetadataScope) ProtoMessage() {}

func (x *NamespaceReq_Delete_MetadataScope) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_queries_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceReq_Delete_MetadataScope.ProtoReflect.Descriptor instead.
func (*NamespaceReq_Delete_MetadataScope) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_queries_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *NamespaceReq_Delete_MetadataScope) GetScoped() isNamespaceReq_Delete_MetadataScope_Scoped {
	if x != nil {
		return x.Scoped
	}
	return nil
}

func (x *NamespaceReq_Delete_MetadataScope) GetUid() string {
	if x != nil {
		if x, ok := x.Scoped.(*NamespaceReq_Delete_MetadataScope_Uid); ok {
			return x.Uid
		}
	}
	return ""
}

func (x *NamespaceReq_Delete_MetadataScope) GetName() string {
	if x != nil {
		if x, ok := x.Scoped.(*NamespaceReq_Delete_MetadataScope_Name); ok {
			return x.Name
		}
	}
	return ""
}

type isNamespaceReq_Delete_MetadataScope_Scoped interface {
	isNamespaceReq_Delete_MetadataScope_Scoped()
}

type NamespaceReq_Delete_MetadataScope_Uid struct {
	// uid: unique identifier
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3,oneof"`
}

type NamespaceReq_Delete_MetadataScope_Name struct {
	// name: resource name
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*NamespaceReq_Delete_MetadataScope_Uid) isNamespaceReq_Delete_MetadataScope_Scoped() {}

func (*NamespaceReq_Delete_MetadataScope_Name) isNamespaceReq_Delete_MetadataScope_Scoped() {}

// Namespace: namespace to delete
type NamespaceReq_Delete_Namespace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// metadata: metadata for scoping
	Metadata      *NamespaceReq_Delete_MetadataScope `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceReq_Delete_Namespace) Reset() {
	*x = NamespaceReq_Delete_Namespace{}
	mi := &file_sgroups_v1_queries_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceReq_Delete_Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceReq_Delete_Namespace) ProtoMessage() {}

func (x *NamespaceReq_Delete_Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_queries_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceReq_Delete_Namespace.ProtoReflect.Descriptor instead.
func (*NamespaceReq_Delete_Namespace) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_queries_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *NamespaceReq_Delete_Namespace) GetMetadata() *NamespaceReq_Delete_MetadataScope {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_sgroups_v1_queries_proto protoreflect.FileDescriptor

const file_sgroups_v1_queries_proto_rawDesc = "" +
	"\n" +
	"\x18sgroups/v1/queries.proto\x12\n" +
	"sgroups.v1\x1a\x1bbuf/validate/validate.proto\x1a\x18sgroups/v1/domains.proto\"\xa6\x06\n" +
	"\fNamespaceReq\x1a\xa6\x02\n" +
	"\bSelector\x12V\n" +
	"\x0efield_selector\x18\x01 \x01(\v2/.sgroups.v1.NamespaceReq.Selector.FieldSelectorR\rfieldSelector\x12[\n" +
	"\x0elabel_selector\x18\x02 \x03(\v24.sgroups.v1.NamespaceReq.Selector.LabelSelectorEntryR\rlabelSelector\x1a#\n" +
	"\rFieldSelector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aG\n" +
	"\x06Upsert\x12=\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2\x15.sgroups.v1.NamespaceB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"namespaces\x1a\x80\x02\n" +
	"\x06Delete\x12Q\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2).sgroups.v1.NamespaceReq.Delete.NamespaceB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"namespaces\x1aC\n" +
	"\rMetadataScope\x12\x12\n" +
	"\x03uid\x18\x01 \x01(\tH\x00R\x03uid\x12\x14\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04nameB\b\n" +
	"\x06scoped\x1a^\n" +
	"\tNamespace\x12Q\n" +
	"\bmetadata\x18\x01 \x01(\v2-.sgroups.v1.NamespaceReq.Delete.MetadataScopeB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x1aO\n" +
	"\x04List\x12G\n" +
	"\tselectors\x18\x01 \x03(\v2!.sgroups.v1.NamespaceReq.SelectorB\x06\xbaH\x03\xc8\x01\x01R\tselectors\x1aP\n" +
	"\x05Watch\x12G\n" +
	"\tselectors\x18\x01 \x03(\v2!.sgroups.v1.NamespaceReq.SelectorB\x06\xbaH\x03\xc8\x01\x01R\tselectorsBDZBgithub.com/PRO-Robotech/sgroups-proto/pkg/api/sgroups/v1;sgroupsv1b\x06proto3"

var (
	file_sgroups_v1_queries_proto_rawDescOnce sync.Once
	file_sgroups_v1_queries_proto_rawDescData []byte
)

func file_sgroups_v1_queries_proto_rawDescGZIP() []byte {
	file_sgroups_v1_queries_proto_rawDescOnce.Do(func() {
		file_sgroups_v1_queries_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sgroups_v1_queries_proto_rawDesc), len(file_sgroups_v1_queries_proto_rawDesc)))
	})
	return file_sgroups_v1_queries_proto_rawDescData
}

var file_sgroups_v1_queries_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sgroups_v1_queries_proto_goTypes = []any{
	(*NamespaceReq)(nil),                        // 0: sgroups.v1.NamespaceReq
	(*NamespaceReq_Selector)(nil),               // 1: sgroups.v1.NamespaceReq.Selector
	(*NamespaceReq_Upsert)(nil),                 // 2: sgroups.v1.NamespaceReq.Upsert
	(*NamespaceReq_Delete)(nil),                 // 3: sgroups.v1.NamespaceReq.Delete
	(*NamespaceReq_List)(nil),                   // 4: sgroups.v1.NamespaceReq.List
	(*NamespaceReq_Watch)(nil),                  // 5: sgroups.v1.NamespaceReq.Watch
	(*NamespaceReq_Selector_FieldSelector)(nil), // 6: sgroups.v1.NamespaceReq.Selector.FieldSelector
	nil, // 7: sgroups.v1.NamespaceReq.Selector.LabelSelectorEntry
	(*NamespaceReq_Delete_MetadataScope)(nil), // 8: sgroups.v1.NamespaceReq.Delete.MetadataScope
	(*NamespaceReq_Delete_Namespace)(nil),     // 9: sgroups.v1.NamespaceReq.Delete.Namespace
	(*Namespace)(nil),                         // 10: sgroups.v1.Namespace
}
var file_sgroups_v1_queries_proto_depIdxs = []int32{
	6,  // 0: sgroups.v1.NamespaceReq.Selector.field_selector:type_name -> sgroups.v1.NamespaceReq.Selector.FieldSelector
	7,  // 1: sgroups.v1.NamespaceReq.Selector.label_selector:type_name -> sgroups.v1.NamespaceReq.Selector.LabelSelectorEntry
	10, // 2: sgroups.v1.NamespaceReq.Upsert.namespaces:type_name -> sgroups.v1.Namespace
	9,  // 3: sgroups.v1.NamespaceReq.Delete.namespaces:type_name -> sgroups.v1.NamespaceReq.Delete.Namespace
	1,  // 4: sgroups.v1.NamespaceReq.List.selectors:type_name -> sgroups.v1.NamespaceReq.Selector
	1,  // 5: sgroups.v1.NamespaceReq.Watch.selectors:type_name -> sgroups.v1.NamespaceReq.Selector
	8,  // 6: sgroups.v1.NamespaceReq.Delete.Namespace.metadata:type_name -> sgroups.v1.NamespaceReq.Delete.MetadataScope
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_sgroups_v1_queries_proto_init() }
func file_sgroups_v1_queries_proto_init() {
	if File_sgroups_v1_queries_proto != nil {
		return
	}
	file_sgroups_v1_domains_proto_init()
	file_sgroups_v1_queries_proto_msgTypes[8].OneofWrappers = []any{
		(*NamespaceReq_Delete_MetadataScope_Uid)(nil),
		(*NamespaceReq_Delete_MetadataScope_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgroups_v1_queries_proto_rawDesc), len(file_sgroups_v1_queries_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sgroups_v1_queries_proto_goTypes,
		DependencyIndexes: file_sgroups_v1_queries_proto_depIdxs,
		MessageInfos:      file_sgroups_v1_queries_proto_msgTypes,
	}.Build()
	File_sgroups_v1_queries_proto = out.File
	file_sgroups_v1_queries_proto_goTypes = nil
	file_sgroups_v1_queries_proto_depIdxs = nil
}
