// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: sgroups/v1/services.proto

package sgroupsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SGroupsNamespaceAPI_Upsert_FullMethodName = "/sgroups.v1.SGroupsNamespaceAPI/Upsert"
	SGroupsNamespaceAPI_Delete_FullMethodName = "/sgroups.v1.SGroupsNamespaceAPI/Delete"
	SGroupsNamespaceAPI_List_FullMethodName   = "/sgroups.v1.SGroupsNamespaceAPI/List"
	SGroupsNamespaceAPI_Watch_FullMethodName  = "/sgroups.v1.SGroupsNamespaceAPI/Watch"
)

// SGroupsNamespaceAPIClient is the client API for SGroupsNamespaceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsNamespaceAPI: SGroups namespaces API
type SGroupsNamespaceAPIClient interface {
	// Upsert: Create or update namespace(es)
	Upsert(ctx context.Context, in *NamespaceReq_Upsert, opts ...grpc.CallOption) (*NamespaceResp_Upsert, error)
	// Delete: Delete namespace(es)
	Delete(ctx context.Context, in *NamespaceReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List namespace(es)
	List(ctx context.Context, in *NamespaceReq_List, opts ...grpc.CallOption) (*NamespaceResp_List, error)
	// Watch: Watch namespace(es)
	Watch(ctx context.Context, in *NamespaceReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NamespaceResp_Watch], error)
}

type sGroupsNamespaceAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsNamespaceAPIClient(cc grpc.ClientConnInterface) SGroupsNamespaceAPIClient {
	return &sGroupsNamespaceAPIClient{cc}
}

func (c *sGroupsNamespaceAPIClient) Upsert(ctx context.Context, in *NamespaceReq_Upsert, opts ...grpc.CallOption) (*NamespaceResp_Upsert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceResp_Upsert)
	err := c.cc.Invoke(ctx, SGroupsNamespaceAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNamespaceAPIClient) Delete(ctx context.Context, in *NamespaceReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsNamespaceAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNamespaceAPIClient) List(ctx context.Context, in *NamespaceReq_List, opts ...grpc.CallOption) (*NamespaceResp_List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceResp_List)
	err := c.cc.Invoke(ctx, SGroupsNamespaceAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNamespaceAPIClient) Watch(ctx context.Context, in *NamespaceReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NamespaceResp_Watch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsNamespaceAPI_ServiceDesc.Streams[0], SGroupsNamespaceAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NamespaceReq_Watch, NamespaceResp_Watch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsNamespaceAPI_WatchClient = grpc.ServerStreamingClient[NamespaceResp_Watch]

// SGroupsNamespaceAPIServer is the server API for SGroupsNamespaceAPI service.
// All implementations must embed UnimplementedSGroupsNamespaceAPIServer
// for forward compatibility.
//
// SGroupsNamespaceAPI: SGroups namespaces API
type SGroupsNamespaceAPIServer interface {
	// Upsert: Create or update namespace(es)
	Upsert(context.Context, *NamespaceReq_Upsert) (*NamespaceResp_Upsert, error)
	// Delete: Delete namespace(es)
	Delete(context.Context, *NamespaceReq_Delete) (*emptypb.Empty, error)
	// List: List namespace(es)
	List(context.Context, *NamespaceReq_List) (*NamespaceResp_List, error)
	// Watch: Watch namespace(es)
	Watch(*NamespaceReq_Watch, grpc.ServerStreamingServer[NamespaceResp_Watch]) error
	mustEmbedUnimplementedSGroupsNamespaceAPIServer()
}

// UnimplementedSGroupsNamespaceAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsNamespaceAPIServer struct{}

func (UnimplementedSGroupsNamespaceAPIServer) Upsert(context.Context, *NamespaceReq_Upsert) (*NamespaceResp_Upsert, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsNamespaceAPIServer) Delete(context.Context, *NamespaceReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsNamespaceAPIServer) List(context.Context, *NamespaceReq_List) (*NamespaceResp_List, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsNamespaceAPIServer) Watch(*NamespaceReq_Watch, grpc.ServerStreamingServer[NamespaceResp_Watch]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsNamespaceAPIServer) mustEmbedUnimplementedSGroupsNamespaceAPIServer() {}
func (UnimplementedSGroupsNamespaceAPIServer) testEmbeddedByValue()                             {}

// UnsafeSGroupsNamespaceAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsNamespaceAPIServer will
// result in compilation errors.
type UnsafeSGroupsNamespaceAPIServer interface {
	mustEmbedUnimplementedSGroupsNamespaceAPIServer()
}

func RegisterSGroupsNamespaceAPIServer(s grpc.ServiceRegistrar, srv SGroupsNamespaceAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsNamespaceAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsNamespaceAPI_ServiceDesc, srv)
}

func _SGroupsNamespaceAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNamespaceAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNamespaceAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNamespaceAPIServer).Upsert(ctx, req.(*NamespaceReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNamespaceAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNamespaceAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNamespaceAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNamespaceAPIServer).Delete(ctx, req.(*NamespaceReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNamespaceAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNamespaceAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNamespaceAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNamespaceAPIServer).List(ctx, req.(*NamespaceReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNamespaceAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NamespaceReq_Watch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsNamespaceAPIServer).Watch(m, &grpc.GenericServerStream[NamespaceReq_Watch, NamespaceResp_Watch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsNamespaceAPI_WatchServer = grpc.ServerStreamingServer[NamespaceResp_Watch]

// SGroupsNamespaceAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsNamespaceAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsNamespaceAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsNamespaceAPI",
	HandlerType: (*SGroupsNamespaceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsNamespaceAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsNamespaceAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsNamespaceAPI_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsNamespaceAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}

const (
	SGroupsAddressGroupsAPI_Upsert_FullMethodName = "/sgroups.v1.SGroupsAddressGroupsAPI/Upsert"
	SGroupsAddressGroupsAPI_Delete_FullMethodName = "/sgroups.v1.SGroupsAddressGroupsAPI/Delete"
	SGroupsAddressGroupsAPI_List_FullMethodName   = "/sgroups.v1.SGroupsAddressGroupsAPI/List"
	SGroupsAddressGroupsAPI_Watch_FullMethodName  = "/sgroups.v1.SGroupsAddressGroupsAPI/Watch"
)

// SGroupsAddressGroupsAPIClient is the client API for SGroupsAddressGroupsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsAddressGroupsAPI: SGroups AddressGroups API
type SGroupsAddressGroupsAPIClient interface {
	// Upsert: Create or update address group(s)
	Upsert(ctx context.Context, in *AddressGroupReq_Upsert, opts ...grpc.CallOption) (*AddressGroupResp_Upsert, error)
	// Delete: Delete address group(s)
	Delete(ctx context.Context, in *AddressGroupReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List address group(s)
	List(ctx context.Context, in *AddressGroupReq_List, opts ...grpc.CallOption) (*AddressGroupResp_List, error)
	// Watch: Watch address group(s)
	Watch(ctx context.Context, in *AddressGroupReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AddressGroupResp_Watch], error)
}

type sGroupsAddressGroupsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsAddressGroupsAPIClient(cc grpc.ClientConnInterface) SGroupsAddressGroupsAPIClient {
	return &sGroupsAddressGroupsAPIClient{cc}
}

func (c *sGroupsAddressGroupsAPIClient) Upsert(ctx context.Context, in *AddressGroupReq_Upsert, opts ...grpc.CallOption) (*AddressGroupResp_Upsert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressGroupResp_Upsert)
	err := c.cc.Invoke(ctx, SGroupsAddressGroupsAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsAddressGroupsAPIClient) Delete(ctx context.Context, in *AddressGroupReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsAddressGroupsAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsAddressGroupsAPIClient) List(ctx context.Context, in *AddressGroupReq_List, opts ...grpc.CallOption) (*AddressGroupResp_List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressGroupResp_List)
	err := c.cc.Invoke(ctx, SGroupsAddressGroupsAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsAddressGroupsAPIClient) Watch(ctx context.Context, in *AddressGroupReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AddressGroupResp_Watch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsAddressGroupsAPI_ServiceDesc.Streams[0], SGroupsAddressGroupsAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AddressGroupReq_Watch, AddressGroupResp_Watch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsAddressGroupsAPI_WatchClient = grpc.ServerStreamingClient[AddressGroupResp_Watch]

// SGroupsAddressGroupsAPIServer is the server API for SGroupsAddressGroupsAPI service.
// All implementations must embed UnimplementedSGroupsAddressGroupsAPIServer
// for forward compatibility.
//
// SGroupsAddressGroupsAPI: SGroups AddressGroups API
type SGroupsAddressGroupsAPIServer interface {
	// Upsert: Create or update address group(s)
	Upsert(context.Context, *AddressGroupReq_Upsert) (*AddressGroupResp_Upsert, error)
	// Delete: Delete address group(s)
	Delete(context.Context, *AddressGroupReq_Delete) (*emptypb.Empty, error)
	// List: List address group(s)
	List(context.Context, *AddressGroupReq_List) (*AddressGroupResp_List, error)
	// Watch: Watch address group(s)
	Watch(*AddressGroupReq_Watch, grpc.ServerStreamingServer[AddressGroupResp_Watch]) error
	mustEmbedUnimplementedSGroupsAddressGroupsAPIServer()
}

// UnimplementedSGroupsAddressGroupsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsAddressGroupsAPIServer struct{}

func (UnimplementedSGroupsAddressGroupsAPIServer) Upsert(context.Context, *AddressGroupReq_Upsert) (*AddressGroupResp_Upsert, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsAddressGroupsAPIServer) Delete(context.Context, *AddressGroupReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsAddressGroupsAPIServer) List(context.Context, *AddressGroupReq_List) (*AddressGroupResp_List, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsAddressGroupsAPIServer) Watch(*AddressGroupReq_Watch, grpc.ServerStreamingServer[AddressGroupResp_Watch]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsAddressGroupsAPIServer) mustEmbedUnimplementedSGroupsAddressGroupsAPIServer() {
}
func (UnimplementedSGroupsAddressGroupsAPIServer) testEmbeddedByValue() {}

// UnsafeSGroupsAddressGroupsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsAddressGroupsAPIServer will
// result in compilation errors.
type UnsafeSGroupsAddressGroupsAPIServer interface {
	mustEmbedUnimplementedSGroupsAddressGroupsAPIServer()
}

func RegisterSGroupsAddressGroupsAPIServer(s grpc.ServiceRegistrar, srv SGroupsAddressGroupsAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsAddressGroupsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsAddressGroupsAPI_ServiceDesc, srv)
}

func _SGroupsAddressGroupsAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressGroupReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsAddressGroupsAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsAddressGroupsAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsAddressGroupsAPIServer).Upsert(ctx, req.(*AddressGroupReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsAddressGroupsAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressGroupReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsAddressGroupsAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsAddressGroupsAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsAddressGroupsAPIServer).Delete(ctx, req.(*AddressGroupReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsAddressGroupsAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressGroupReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsAddressGroupsAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsAddressGroupsAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsAddressGroupsAPIServer).List(ctx, req.(*AddressGroupReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsAddressGroupsAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AddressGroupReq_Watch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsAddressGroupsAPIServer).Watch(m, &grpc.GenericServerStream[AddressGroupReq_Watch, AddressGroupResp_Watch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsAddressGroupsAPI_WatchServer = grpc.ServerStreamingServer[AddressGroupResp_Watch]

// SGroupsAddressGroupsAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsAddressGroupsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsAddressGroupsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsAddressGroupsAPI",
	HandlerType: (*SGroupsAddressGroupsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsAddressGroupsAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsAddressGroupsAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsAddressGroupsAPI_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsAddressGroupsAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}

const (
	SGroupsHostsAPI_Upsert_FullMethodName      = "/sgroups.v1.SGroupsHostsAPI/Upsert"
	SGroupsHostsAPI_Delete_FullMethodName      = "/sgroups.v1.SGroupsHostsAPI/Delete"
	SGroupsHostsAPI_List_FullMethodName        = "/sgroups.v1.SGroupsHostsAPI/List"
	SGroupsHostsAPI_Watch_FullMethodName       = "/sgroups.v1.SGroupsHostsAPI/Watch"
	SGroupsHostsAPI_UpdIPs_FullMethodName      = "/sgroups.v1.SGroupsHostsAPI/UpdIPs"
	SGroupsHostsAPI_UpdMetaInfo_FullMethodName = "/sgroups.v1.SGroupsHostsAPI/UpdMetaInfo"
)

// SGroupsHostsAPIClient is the client API for SGroupsHostsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsHostsAPI: SGroups Hosts API
type SGroupsHostsAPIClient interface {
	// Upsert: Create or update host(s)
	Upsert(ctx context.Context, in *HostReq_Upsert, opts ...grpc.CallOption) (*HostResp_Upsert, error)
	// Delete: Delete host(s)
	Delete(ctx context.Context, in *HostReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List host(s)
	List(ctx context.Context, in *HostReq_List, opts ...grpc.CallOption) (*HostResp_List, error)
	// Watch: Watch host(s)
	Watch(ctx context.Context, in *HostReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HostResp_Watch], error)
	// UpdIPs: Update host(s) IPs
	UpdIPs(ctx context.Context, in *HostReq_UpdIPs, opts ...grpc.CallOption) (*HostResp_UpdIPs, error)
	// UpdMetaInfo: Update host(s) meta information
	UpdMetaInfo(ctx context.Context, in *HostReq_UpdMetaInfo, opts ...grpc.CallOption) (*HostResp_UpdMetaInfo, error)
}

type sGroupsHostsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsHostsAPIClient(cc grpc.ClientConnInterface) SGroupsHostsAPIClient {
	return &sGroupsHostsAPIClient{cc}
}

func (c *sGroupsHostsAPIClient) Upsert(ctx context.Context, in *HostReq_Upsert, opts ...grpc.CallOption) (*HostResp_Upsert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostResp_Upsert)
	err := c.cc.Invoke(ctx, SGroupsHostsAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsHostsAPIClient) Delete(ctx context.Context, in *HostReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsHostsAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsHostsAPIClient) List(ctx context.Context, in *HostReq_List, opts ...grpc.CallOption) (*HostResp_List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostResp_List)
	err := c.cc.Invoke(ctx, SGroupsHostsAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsHostsAPIClient) Watch(ctx context.Context, in *HostReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HostResp_Watch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsHostsAPI_ServiceDesc.Streams[0], SGroupsHostsAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HostReq_Watch, HostResp_Watch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsHostsAPI_WatchClient = grpc.ServerStreamingClient[HostResp_Watch]

func (c *sGroupsHostsAPIClient) UpdIPs(ctx context.Context, in *HostReq_UpdIPs, opts ...grpc.CallOption) (*HostResp_UpdIPs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostResp_UpdIPs)
	err := c.cc.Invoke(ctx, SGroupsHostsAPI_UpdIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsHostsAPIClient) UpdMetaInfo(ctx context.Context, in *HostReq_UpdMetaInfo, opts ...grpc.CallOption) (*HostResp_UpdMetaInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostResp_UpdMetaInfo)
	err := c.cc.Invoke(ctx, SGroupsHostsAPI_UpdMetaInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SGroupsHostsAPIServer is the server API for SGroupsHostsAPI service.
// All implementations must embed UnimplementedSGroupsHostsAPIServer
// for forward compatibility.
//
// SGroupsHostsAPI: SGroups Hosts API
type SGroupsHostsAPIServer interface {
	// Upsert: Create or update host(s)
	Upsert(context.Context, *HostReq_Upsert) (*HostResp_Upsert, error)
	// Delete: Delete host(s)
	Delete(context.Context, *HostReq_Delete) (*emptypb.Empty, error)
	// List: List host(s)
	List(context.Context, *HostReq_List) (*HostResp_List, error)
	// Watch: Watch host(s)
	Watch(*HostReq_Watch, grpc.ServerStreamingServer[HostResp_Watch]) error
	// UpdIPs: Update host(s) IPs
	UpdIPs(context.Context, *HostReq_UpdIPs) (*HostResp_UpdIPs, error)
	// UpdMetaInfo: Update host(s) meta information
	UpdMetaInfo(context.Context, *HostReq_UpdMetaInfo) (*HostResp_UpdMetaInfo, error)
	mustEmbedUnimplementedSGroupsHostsAPIServer()
}

// UnimplementedSGroupsHostsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsHostsAPIServer struct{}

func (UnimplementedSGroupsHostsAPIServer) Upsert(context.Context, *HostReq_Upsert) (*HostResp_Upsert, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsHostsAPIServer) Delete(context.Context, *HostReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsHostsAPIServer) List(context.Context, *HostReq_List) (*HostResp_List, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsHostsAPIServer) Watch(*HostReq_Watch, grpc.ServerStreamingServer[HostResp_Watch]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsHostsAPIServer) UpdIPs(context.Context, *HostReq_UpdIPs) (*HostResp_UpdIPs, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdIPs not implemented")
}
func (UnimplementedSGroupsHostsAPIServer) UpdMetaInfo(context.Context, *HostReq_UpdMetaInfo) (*HostResp_UpdMetaInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdMetaInfo not implemented")
}
func (UnimplementedSGroupsHostsAPIServer) mustEmbedUnimplementedSGroupsHostsAPIServer() {}
func (UnimplementedSGroupsHostsAPIServer) testEmbeddedByValue()                         {}

// UnsafeSGroupsHostsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsHostsAPIServer will
// result in compilation errors.
type UnsafeSGroupsHostsAPIServer interface {
	mustEmbedUnimplementedSGroupsHostsAPIServer()
}

func RegisterSGroupsHostsAPIServer(s grpc.ServiceRegistrar, srv SGroupsHostsAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsHostsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsHostsAPI_ServiceDesc, srv)
}

func _SGroupsHostsAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostsAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostsAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostsAPIServer).Upsert(ctx, req.(*HostReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsHostsAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostsAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostsAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostsAPIServer).Delete(ctx, req.(*HostReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsHostsAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostsAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostsAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostsAPIServer).List(ctx, req.(*HostReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsHostsAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HostReq_Watch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsHostsAPIServer).Watch(m, &grpc.GenericServerStream[HostReq_Watch, HostResp_Watch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsHostsAPI_WatchServer = grpc.ServerStreamingServer[HostResp_Watch]

func _SGroupsHostsAPI_UpdIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostReq_UpdIPs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostsAPIServer).UpdIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostsAPI_UpdIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostsAPIServer).UpdIPs(ctx, req.(*HostReq_UpdIPs))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsHostsAPI_UpdMetaInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostReq_UpdMetaInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostsAPIServer).UpdMetaInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostsAPI_UpdMetaInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostsAPIServer).UpdMetaInfo(ctx, req.(*HostReq_UpdMetaInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// SGroupsHostsAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsHostsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsHostsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsHostsAPI",
	HandlerType: (*SGroupsHostsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsHostsAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsHostsAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsHostsAPI_List_Handler,
		},
		{
			MethodName: "UpdIPs",
			Handler:    _SGroupsHostsAPI_UpdIPs_Handler,
		},
		{
			MethodName: "UpdMetaInfo",
			Handler:    _SGroupsHostsAPI_UpdMetaInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsHostsAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}
