// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: sgroups/v1/service.proto

package sgroupsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SgroupsAPI_NameSpaceUpsert_FullMethodName = "/sgroups.v1.SgroupsAPI/NameSpaceUpsert"
)

// SgroupsAPIClient is the client API for SgroupsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SgroupsAPI: Security Groups API service
type SgroupsAPIClient interface {
	// NameSpaceUpsert: Create or update tenant namespace(es)
	NameSpaceUpsert(ctx context.Context, in *NamespaceList, opts ...grpc.CallOption) (*NamespaceList, error)
}

type sgroupsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSgroupsAPIClient(cc grpc.ClientConnInterface) SgroupsAPIClient {
	return &sgroupsAPIClient{cc}
}

func (c *sgroupsAPIClient) NameSpaceUpsert(ctx context.Context, in *NamespaceList, opts ...grpc.CallOption) (*NamespaceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceList)
	err := c.cc.Invoke(ctx, SgroupsAPI_NameSpaceUpsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SgroupsAPIServer is the server API for SgroupsAPI service.
// All implementations must embed UnimplementedSgroupsAPIServer
// for forward compatibility.
//
// SgroupsAPI: Security Groups API service
type SgroupsAPIServer interface {
	// NameSpaceUpsert: Create or update tenant namespace(es)
	NameSpaceUpsert(context.Context, *NamespaceList) (*NamespaceList, error)
	mustEmbedUnimplementedSgroupsAPIServer()
}

// UnimplementedSgroupsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSgroupsAPIServer struct{}

func (UnimplementedSgroupsAPIServer) NameSpaceUpsert(context.Context, *NamespaceList) (*NamespaceList, error) {
	return nil, status.Error(codes.Unimplemented, "method NameSpaceUpsert not implemented")
}
func (UnimplementedSgroupsAPIServer) mustEmbedUnimplementedSgroupsAPIServer() {}
func (UnimplementedSgroupsAPIServer) testEmbeddedByValue()                    {}

// UnsafeSgroupsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SgroupsAPIServer will
// result in compilation errors.
type UnsafeSgroupsAPIServer interface {
	mustEmbedUnimplementedSgroupsAPIServer()
}

func RegisterSgroupsAPIServer(s grpc.ServiceRegistrar, srv SgroupsAPIServer) {
	// If the following call panics, it indicates UnimplementedSgroupsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SgroupsAPI_ServiceDesc, srv)
}

func _SgroupsAPI_NameSpaceUpsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SgroupsAPIServer).NameSpaceUpsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SgroupsAPI_NameSpaceUpsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SgroupsAPIServer).NameSpaceUpsert(ctx, req.(*NamespaceList))
	}
	return interceptor(ctx, in, info, handler)
}

// SgroupsAPI_ServiceDesc is the grpc.ServiceDesc for SgroupsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SgroupsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SgroupsAPI",
	HandlerType: (*SgroupsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NameSpaceUpsert",
			Handler:    _SgroupsAPI_NameSpaceUpsert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sgroups/v1/service.proto",
}
