// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sgroups/v1/services.proto

package sgroupsv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_sgroups_v1_services_proto protoreflect.FileDescriptor

const file_sgroups_v1_services_proto_rawDesc = "" +
	"\n" +
	"\x19sgroups/v1/services.proto\x12\n" +
	"sgroups.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x18sgroups/v1/queries.proto2\x8e\x05\n" +
	"\x13SGroupsNamespaceAPI\x12\xa2\x01\n" +
	"\x06Upsert\x12\x1f.sgroups.v1.NamespaceReq.Upsert\x1a .sgroups.v1.NamespaceResp.Upsert\"U\x92A3\n" +
	"\tNamespace\x1a&Upsert: Create or update namespace(es)\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/namespace/upsert\x12\x8e\x01\n" +
	"\x06Delete\x12\x1f.sgroups.v1.NamespaceReq.Delete\x1a\x16.google.protobuf.Empty\"K\x92A)\n" +
	"\tNamespace\x1a\x1cDelete: Delete namespace(es)\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/namespace/delete\x12\x8c\x01\n" +
	"\x04List\x12\x1d.sgroups.v1.NamespaceReq.List\x1a\x1e.sgroups.v1.NamespaceResp.List\"E\x92A%\n" +
	"\tNamespace\x1a\x18List: List namespace(es)\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/namespace/list\x12\x94\x01\n" +
	"\x05Watch\x12\x1e.sgroups.v1.NamespaceReq.Watch\x1a\x1f.sgroups.v1.NamespaceResp.Watch\"H\x92A'\n" +
	"\tNamespace\x1a\x1aWatch: Watch namespace(es)\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/namespace/watch0\x01\x1a\x1b\x92A\x18\x12\x16Namespace Resource API2\xa7\x05\n" +
	"\x17SGroupsAddressGroupsAPI\x12\xa7\x01\n" +
	"\x06Upsert\x12\".sgroups.v1.AddressGroupReq.Upsert\x1a#.sgroups.v1.AddressGroupResp.Upsert\"T\x92A9\n" +
	"\fAddressGroup\x1a)Upsert: Create or update address group(s)\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/ag/upsert\x12\x90\x01\n" +
	"\x06Delete\x12\".sgroups.v1.AddressGroupReq.Delete\x1a\x16.google.protobuf.Empty\"J\x92A/\n" +
	"\fAddressGroup\x1a\x1fDelete: Delete address group(s)\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/ag/delete\x12\x91\x01\n" +
	"\x04List\x12 .sgroups.v1.AddressGroupReq.List\x1a!.sgroups.v1.AddressGroupResp.List\"D\x92A+\n" +
	"\fAddressGroup\x1a\x1bList: List address group(s)\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/ag/list\x12\x99\x01\n" +
	"\x05Watch\x12!.sgroups.v1.AddressGroupReq.Watch\x1a\".sgroups.v1.AddressGroupResp.Watch\"G\x92A-\n" +
	"\fAddressGroup\x1a\x1dWatch: Watch address group(s)\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/ag/watch0\x01\x1a\x1f\x92A\x1c\x12\x1aAddressGroups Resource APIB\xb0\x01\x92Ai\x12\x12\n" +
	"\vSGroups API2\x031.0*\x01\x012\x10application/json:\x10application/jsonr,\n" +
	"\rDocumentation\x12\x1bhttps://h-bf.prorobotech.ruZBgithub.com/PRO-Robotech/sgroups-proto/pkg/api/sgroups/v1;sgroupsv1b\x06proto3"

var file_sgroups_v1_services_proto_goTypes = []any{
	(*NamespaceReq_Upsert)(nil),     // 0: sgroups.v1.NamespaceReq.Upsert
	(*NamespaceReq_Delete)(nil),     // 1: sgroups.v1.NamespaceReq.Delete
	(*NamespaceReq_List)(nil),       // 2: sgroups.v1.NamespaceReq.List
	(*NamespaceReq_Watch)(nil),      // 3: sgroups.v1.NamespaceReq.Watch
	(*AddressGroupReq_Upsert)(nil),  // 4: sgroups.v1.AddressGroupReq.Upsert
	(*AddressGroupReq_Delete)(nil),  // 5: sgroups.v1.AddressGroupReq.Delete
	(*AddressGroupReq_List)(nil),    // 6: sgroups.v1.AddressGroupReq.List
	(*AddressGroupReq_Watch)(nil),   // 7: sgroups.v1.AddressGroupReq.Watch
	(*NamespaceResp_Upsert)(nil),    // 8: sgroups.v1.NamespaceResp.Upsert
	(*emptypb.Empty)(nil),           // 9: google.protobuf.Empty
	(*NamespaceResp_List)(nil),      // 10: sgroups.v1.NamespaceResp.List
	(*NamespaceResp_Watch)(nil),     // 11: sgroups.v1.NamespaceResp.Watch
	(*AddressGroupResp_Upsert)(nil), // 12: sgroups.v1.AddressGroupResp.Upsert
	(*AddressGroupResp_List)(nil),   // 13: sgroups.v1.AddressGroupResp.List
	(*AddressGroupResp_Watch)(nil),  // 14: sgroups.v1.AddressGroupResp.Watch
}
var file_sgroups_v1_services_proto_depIdxs = []int32{
	0,  // 0: sgroups.v1.SGroupsNamespaceAPI.Upsert:input_type -> sgroups.v1.NamespaceReq.Upsert
	1,  // 1: sgroups.v1.SGroupsNamespaceAPI.Delete:input_type -> sgroups.v1.NamespaceReq.Delete
	2,  // 2: sgroups.v1.SGroupsNamespaceAPI.List:input_type -> sgroups.v1.NamespaceReq.List
	3,  // 3: sgroups.v1.SGroupsNamespaceAPI.Watch:input_type -> sgroups.v1.NamespaceReq.Watch
	4,  // 4: sgroups.v1.SGroupsAddressGroupsAPI.Upsert:input_type -> sgroups.v1.AddressGroupReq.Upsert
	5,  // 5: sgroups.v1.SGroupsAddressGroupsAPI.Delete:input_type -> sgroups.v1.AddressGroupReq.Delete
	6,  // 6: sgroups.v1.SGroupsAddressGroupsAPI.List:input_type -> sgroups.v1.AddressGroupReq.List
	7,  // 7: sgroups.v1.SGroupsAddressGroupsAPI.Watch:input_type -> sgroups.v1.AddressGroupReq.Watch
	8,  // 8: sgroups.v1.SGroupsNamespaceAPI.Upsert:output_type -> sgroups.v1.NamespaceResp.Upsert
	9,  // 9: sgroups.v1.SGroupsNamespaceAPI.Delete:output_type -> google.protobuf.Empty
	10, // 10: sgroups.v1.SGroupsNamespaceAPI.List:output_type -> sgroups.v1.NamespaceResp.List
	11, // 11: sgroups.v1.SGroupsNamespaceAPI.Watch:output_type -> sgroups.v1.NamespaceResp.Watch
	12, // 12: sgroups.v1.SGroupsAddressGroupsAPI.Upsert:output_type -> sgroups.v1.AddressGroupResp.Upsert
	9,  // 13: sgroups.v1.SGroupsAddressGroupsAPI.Delete:output_type -> google.protobuf.Empty
	13, // 14: sgroups.v1.SGroupsAddressGroupsAPI.List:output_type -> sgroups.v1.AddressGroupResp.List
	14, // 15: sgroups.v1.SGroupsAddressGroupsAPI.Watch:output_type -> sgroups.v1.AddressGroupResp.Watch
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_sgroups_v1_services_proto_init() }
func file_sgroups_v1_services_proto_init() {
	if File_sgroups_v1_services_proto != nil {
		return
	}
	file_sgroups_v1_queries_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgroups_v1_services_proto_rawDesc), len(file_sgroups_v1_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sgroups_v1_services_proto_goTypes,
		DependencyIndexes: file_sgroups_v1_services_proto_depIdxs,
	}.Build()
	File_sgroups_v1_services_proto = out.File
	file_sgroups_v1_services_proto_goTypes = nil
	file_sgroups_v1_services_proto_depIdxs = nil
}
