// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sgroups/v1/services.proto

package sgroupsv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_sgroups_v1_services_proto protoreflect.FileDescriptor

const file_sgroups_v1_services_proto_rawDesc = "" +
	"\n" +
	"\x19sgroups/v1/services.proto\x12\n" +
	"sgroups.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x18sgroups/v1/queries.proto2\x92\x05\n" +
	"\x13SGroupsNamespaceAPI\x12\xa3\x01\n" +
	"\x06Upsert\x12\x1f.sgroups.v1.NamespaceReq.Upsert\x1a .sgroups.v1.NamespaceResp.Upsert\"V\x92A3\n" +
	"\tNamespace\x1a&Upsert: Create or update namespace(es)\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/namespaces/upsert\x12\x8f\x01\n" +
	"\x06Delete\x12\x1f.sgroups.v1.NamespaceReq.Delete\x1a\x16.google.protobuf.Empty\"L\x92A)\n" +
	"\tNamespace\x1a\x1cDelete: Delete namespace(es)\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/namespaces/delete\x12\x8d\x01\n" +
	"\x04List\x12\x1d.sgroups.v1.NamespaceReq.List\x1a\x1e.sgroups.v1.NamespaceResp.List\"F\x92A%\n" +
	"\tNamespace\x1a\x18List: List namespace(es)\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/namespaces/list\x12\x95\x01\n" +
	"\x05Watch\x12\x1e.sgroups.v1.NamespaceReq.Watch\x1a\x1f.sgroups.v1.NamespaceResp.Watch\"I\x92A'\n" +
	"\tNamespace\x1a\x1aWatch: Watch namespace(es)\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/namespaces/watch0\x01\x1a\x1b\x92A\x18\x12\x16Namespace Resource API2\xd7\x05\n" +
	"\x17SGroupsAddressGroupsAPI\x12\xb3\x01\n" +
	"\x06Upsert\x12\".sgroups.v1.AddressGroupReq.Upsert\x1a#.sgroups.v1.AddressGroupResp.Upsert\"`\x92A9\n" +
	"\fAddressGroup\x1a)Upsert: Create or update address group(s)\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/address-groups/upsert\x12\x9c\x01\n" +
	"\x06Delete\x12\".sgroups.v1.AddressGroupReq.Delete\x1a\x16.google.protobuf.Empty\"V\x92A/\n" +
	"\fAddressGroup\x1a\x1fDelete: Delete address group(s)\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/address-groups/delete\x12\x9d\x01\n" +
	"\x04List\x12 .sgroups.v1.AddressGroupReq.List\x1a!.sgroups.v1.AddressGroupResp.List\"P\x92A+\n" +
	"\fAddressGroup\x1a\x1bList: List address group(s)\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/address-groups/list\x12\xa5\x01\n" +
	"\x05Watch\x12!.sgroups.v1.AddressGroupReq.Watch\x1a\".sgroups.v1.AddressGroupResp.Watch\"S\x92A-\n" +
	"\fAddressGroup\x1a\x1dWatch: Watch address group(s)\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/address-groups/watch0\x01\x1a\x1f\x92A\x1c\x12\x1aAddressGroups Resource API2\xe6\x04\n" +
	"\x12SGroupsNetworksAPI\x12\x98\x01\n" +
	"\x06Upsert\x12\x1d.sgroups.v1.NetworkReq.Upsert\x1a\x1e.sgroups.v1.NetworkResp.Upsert\"O\x92A.\n" +
	"\aNetwork\x1a#Upsert: Create or update network(s)\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/networks/upsert\x12\x86\x01\n" +
	"\x06Delete\x12\x1d.sgroups.v1.NetworkReq.Delete\x1a\x16.google.protobuf.Empty\"E\x92A$\n" +
	"\aNetwork\x1a\x19Delete: Delete network(s)\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/networks/delete\x12\x82\x01\n" +
	"\x04List\x12\x1b.sgroups.v1.NetworkReq.List\x1a\x1c.sgroups.v1.NetworkResp.List\"?\x92A \n" +
	"\aNetwork\x1a\x15List: List network(s)\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/networks/list\x12\x8a\x01\n" +
	"\x05Watch\x12\x1c.sgroups.v1.NetworkReq.Watch\x1a\x1d.sgroups.v1.NetworkResp.Watch\"B\x92A\"\n" +
	"\aNetwork\x1a\x17Watch: Watch network(s)\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/networks/watch0\x01\x1a\x1a\x92A\x17\x12\x15Networks Resource API2\xd8\x06\n" +
	"\x0fSGroupsHostsAPI\x12\x89\x01\n" +
	"\x06Upsert\x12\x1a.sgroups.v1.HostReq.Upsert\x1a\x1b.sgroups.v1.HostResp.Upsert\"F\x92A(\n" +
	"\x04Host\x1a Upsert: Create or update host(s)\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/hosts/upsert\x12z\n" +
	"\x06Delete\x12\x1a.sgroups.v1.HostReq.Delete\x1a\x16.google.protobuf.Empty\"<\x92A\x1e\n" +
	"\x04Host\x1a\x16Delete: Delete host(s)\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/hosts/delete\x12s\n" +
	"\x04List\x12\x18.sgroups.v1.HostReq.List\x1a\x19.sgroups.v1.HostResp.List\"6\x92A\x1a\n" +
	"\x04Host\x1a\x12List: List host(s)\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/hosts/list\x12{\n" +
	"\x05Watch\x12\x19.sgroups.v1.HostReq.Watch\x1a\x1a.sgroups.v1.HostResp.Watch\"9\x92A\x1c\n" +
	"\x04Host\x1a\x14Watch: Watch host(s)\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/hosts/watch0\x01\x12\x84\x01\n" +
	"\x06UpdIPs\x12\x1a.sgroups.v1.HostReq.UpdIPs\x1a\x1b.sgroups.v1.HostResp.UpdIPs\"A\x92A\"\n" +
	"\x04Host\x1a\x1aUpdIPs: Update host(s) IPs\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/hosts/upd-ips\x12\xaa\x01\n" +
	"\vUpdMetaInfo\x12\x1f.sgroups.v1.HostReq.UpdMetaInfo\x1a .sgroups.v1.HostResp.UpdMetaInfo\"X\x92A4\n" +
	"\x04Host\x1a,UpdMetaInfo: Update host(s) meta information\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/hosts/upd-metainfo\x1a\x17\x92A\x14\x12\x12Hosts Resource API2\xc0\x05\n" +
	"\x15SGroupsHostBindingAPI\x12\xae\x01\n" +
	"\x06Upsert\x12!.sgroups.v1.HostBindingReq.Upsert\x1a\".sgroups.v1.HostBindingResp.Upsert\"]\x92A7\n" +
	"\vHostBinding\x1a(Upsert: Create or update host binding(s)\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/host-bindings/upsert\x12\x98\x01\n" +
	"\x06Delete\x12!.sgroups.v1.HostBindingReq.Delete\x1a\x16.google.protobuf.Empty\"S\x92A-\n" +
	"\vHostBinding\x1a\x1eDelete: Delete host binding(s)\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/host-bindings/delete\x12\x98\x01\n" +
	"\x04List\x12\x1f.sgroups.v1.HostBindingReq.List\x1a .sgroups.v1.HostBindingResp.List\"M\x92A)\n" +
	"\vHostBinding\x1a\x1aList: List host binding(s)\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/host-bindings/list\x12\xa0\x01\n" +
	"\x05Watch\x12 .sgroups.v1.HostBindingReq.Watch\x1a!.sgroups.v1.HostBindingResp.Watch\"P\x92A+\n" +
	"\vHostBinding\x1a\x1cWatch: Watch host binding(s)\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/host-bindings/watch0\x01\x1a\x1d\x92A\x1a\x12\x18HostBinding Resource API2\xff\x05\n" +
	"\x18SGroupsNetworkBindingAPI\x12\xbd\x01\n" +
	"\x06Upsert\x12$.sgroups.v1.NetworkBindingReq.Upsert\x1a%.sgroups.v1.NetworkBindingResp.Upsert\"f\x92A=\n" +
	"\x0eNetworkBinding\x1a+Upsert: Create or update network binding(s)\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/network-bindings/upsert\x12\xa4\x01\n" +
	"\x06Delete\x12$.sgroups.v1.NetworkBindingReq.Delete\x1a\x16.google.protobuf.Empty\"\\\x92A3\n" +
	"\x0eNetworkBinding\x1a!Delete: Delete network binding(s)\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/network-bindings/delete\x12\xa7\x01\n" +
	"\x04List\x12\".sgroups.v1.NetworkBindingReq.List\x1a#.sgroups.v1.NetworkBindingResp.List\"V\x92A/\n" +
	"\x0eNetworkBinding\x1a\x1dList: List network binding(s)\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/network-bindings/list\x12\xaf\x01\n" +
	"\x05Watch\x12#.sgroups.v1.NetworkBindingReq.Watch\x1a$.sgroups.v1.NetworkBindingResp.Watch\"Y\x92A1\n" +
	"\x0eNetworkBinding\x1a\x1fWatch: Watch network binding(s)\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/network-bindings/watch0\x01\x1a \x92A\x1d\x12\x1bNetworkBinding Resource API2\x9f\x04\n" +
	"\x0fSGroupsRulesAPI\x12\x88\x01\n" +
	"\x06Upsert\x12\x1a.sgroups.v1.RuleReq.Upsert\x1a\x1b.sgroups.v1.RuleResp.Upsert\"E\x92A'\n" +
	"\x05Rules\x1a\x1eUpsert: Create or update rules\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/rules/upsert\x12y\n" +
	"\x06Delete\x12\x1a.sgroups.v1.RuleReq.Delete\x1a\x16.google.protobuf.Empty\";\x92A\x1d\n" +
	"\x05Rules\x1a\x14Delete: Delete rules\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/rules/delete\x12r\n" +
	"\x04List\x12\x18.sgroups.v1.RuleReq.List\x1a\x19.sgroups.v1.RuleResp.List\"5\x92A\x19\n" +
	"\x05Rules\x1a\x10List: List rules\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/rules/list\x12z\n" +
	"\x05Watch\x12\x19.sgroups.v1.RuleReq.Watch\x1a\x1a.sgroups.v1.RuleResp.Watch\"8\x92A\x1b\n" +
	"\x05Rules\x1a\x12Watch: Watch rules\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/rules/watch0\x01\x1a\x16\x92A\x13\x12\x11SGroups Rules APIB\xb0\x01\x92Ai\x12\x12\n" +
	"\vSGroups API2\x031.0*\x01\x012\x10application/json:\x10application/jsonr,\n" +
	"\rDocumentation\x12\x1bhttps://h-bf.prorobotech.ruZBgithub.com/PRO-Robotech/sgroups-proto/pkg/api/sgroups/v1;sgroupsv1b\x06proto3"

var file_sgroups_v1_services_proto_goTypes = []any{
	(*NamespaceReq_Upsert)(nil),       // 0: sgroups.v1.NamespaceReq.Upsert
	(*NamespaceReq_Delete)(nil),       // 1: sgroups.v1.NamespaceReq.Delete
	(*NamespaceReq_List)(nil),         // 2: sgroups.v1.NamespaceReq.List
	(*NamespaceReq_Watch)(nil),        // 3: sgroups.v1.NamespaceReq.Watch
	(*AddressGroupReq_Upsert)(nil),    // 4: sgroups.v1.AddressGroupReq.Upsert
	(*AddressGroupReq_Delete)(nil),    // 5: sgroups.v1.AddressGroupReq.Delete
	(*AddressGroupReq_List)(nil),      // 6: sgroups.v1.AddressGroupReq.List
	(*AddressGroupReq_Watch)(nil),     // 7: sgroups.v1.AddressGroupReq.Watch
	(*NetworkReq_Upsert)(nil),         // 8: sgroups.v1.NetworkReq.Upsert
	(*NetworkReq_Delete)(nil),         // 9: sgroups.v1.NetworkReq.Delete
	(*NetworkReq_List)(nil),           // 10: sgroups.v1.NetworkReq.List
	(*NetworkReq_Watch)(nil),          // 11: sgroups.v1.NetworkReq.Watch
	(*HostReq_Upsert)(nil),            // 12: sgroups.v1.HostReq.Upsert
	(*HostReq_Delete)(nil),            // 13: sgroups.v1.HostReq.Delete
	(*HostReq_List)(nil),              // 14: sgroups.v1.HostReq.List
	(*HostReq_Watch)(nil),             // 15: sgroups.v1.HostReq.Watch
	(*HostReq_UpdIPs)(nil),            // 16: sgroups.v1.HostReq.UpdIPs
	(*HostReq_UpdMetaInfo)(nil),       // 17: sgroups.v1.HostReq.UpdMetaInfo
	(*HostBindingReq_Upsert)(nil),     // 18: sgroups.v1.HostBindingReq.Upsert
	(*HostBindingReq_Delete)(nil),     // 19: sgroups.v1.HostBindingReq.Delete
	(*HostBindingReq_List)(nil),       // 20: sgroups.v1.HostBindingReq.List
	(*HostBindingReq_Watch)(nil),      // 21: sgroups.v1.HostBindingReq.Watch
	(*NetworkBindingReq_Upsert)(nil),  // 22: sgroups.v1.NetworkBindingReq.Upsert
	(*NetworkBindingReq_Delete)(nil),  // 23: sgroups.v1.NetworkBindingReq.Delete
	(*NetworkBindingReq_List)(nil),    // 24: sgroups.v1.NetworkBindingReq.List
	(*NetworkBindingReq_Watch)(nil),   // 25: sgroups.v1.NetworkBindingReq.Watch
	(*RuleReq_Upsert)(nil),            // 26: sgroups.v1.RuleReq.Upsert
	(*RuleReq_Delete)(nil),            // 27: sgroups.v1.RuleReq.Delete
	(*RuleReq_List)(nil),              // 28: sgroups.v1.RuleReq.List
	(*RuleReq_Watch)(nil),             // 29: sgroups.v1.RuleReq.Watch
	(*NamespaceResp_Upsert)(nil),      // 30: sgroups.v1.NamespaceResp.Upsert
	(*emptypb.Empty)(nil),             // 31: google.protobuf.Empty
	(*NamespaceResp_List)(nil),        // 32: sgroups.v1.NamespaceResp.List
	(*NamespaceResp_Watch)(nil),       // 33: sgroups.v1.NamespaceResp.Watch
	(*AddressGroupResp_Upsert)(nil),   // 34: sgroups.v1.AddressGroupResp.Upsert
	(*AddressGroupResp_List)(nil),     // 35: sgroups.v1.AddressGroupResp.List
	(*AddressGroupResp_Watch)(nil),    // 36: sgroups.v1.AddressGroupResp.Watch
	(*NetworkResp_Upsert)(nil),        // 37: sgroups.v1.NetworkResp.Upsert
	(*NetworkResp_List)(nil),          // 38: sgroups.v1.NetworkResp.List
	(*NetworkResp_Watch)(nil),         // 39: sgroups.v1.NetworkResp.Watch
	(*HostResp_Upsert)(nil),           // 40: sgroups.v1.HostResp.Upsert
	(*HostResp_List)(nil),             // 41: sgroups.v1.HostResp.List
	(*HostResp_Watch)(nil),            // 42: sgroups.v1.HostResp.Watch
	(*HostResp_UpdIPs)(nil),           // 43: sgroups.v1.HostResp.UpdIPs
	(*HostResp_UpdMetaInfo)(nil),      // 44: sgroups.v1.HostResp.UpdMetaInfo
	(*HostBindingResp_Upsert)(nil),    // 45: sgroups.v1.HostBindingResp.Upsert
	(*HostBindingResp_List)(nil),      // 46: sgroups.v1.HostBindingResp.List
	(*HostBindingResp_Watch)(nil),     // 47: sgroups.v1.HostBindingResp.Watch
	(*NetworkBindingResp_Upsert)(nil), // 48: sgroups.v1.NetworkBindingResp.Upsert
	(*NetworkBindingResp_List)(nil),   // 49: sgroups.v1.NetworkBindingResp.List
	(*NetworkBindingResp_Watch)(nil),  // 50: sgroups.v1.NetworkBindingResp.Watch
	(*RuleResp_Upsert)(nil),           // 51: sgroups.v1.RuleResp.Upsert
	(*RuleResp_List)(nil),             // 52: sgroups.v1.RuleResp.List
	(*RuleResp_Watch)(nil),            // 53: sgroups.v1.RuleResp.Watch
}
var file_sgroups_v1_services_proto_depIdxs = []int32{
	0,  // 0: sgroups.v1.SGroupsNamespaceAPI.Upsert:input_type -> sgroups.v1.NamespaceReq.Upsert
	1,  // 1: sgroups.v1.SGroupsNamespaceAPI.Delete:input_type -> sgroups.v1.NamespaceReq.Delete
	2,  // 2: sgroups.v1.SGroupsNamespaceAPI.List:input_type -> sgroups.v1.NamespaceReq.List
	3,  // 3: sgroups.v1.SGroupsNamespaceAPI.Watch:input_type -> sgroups.v1.NamespaceReq.Watch
	4,  // 4: sgroups.v1.SGroupsAddressGroupsAPI.Upsert:input_type -> sgroups.v1.AddressGroupReq.Upsert
	5,  // 5: sgroups.v1.SGroupsAddressGroupsAPI.Delete:input_type -> sgroups.v1.AddressGroupReq.Delete
	6,  // 6: sgroups.v1.SGroupsAddressGroupsAPI.List:input_type -> sgroups.v1.AddressGroupReq.List
	7,  // 7: sgroups.v1.SGroupsAddressGroupsAPI.Watch:input_type -> sgroups.v1.AddressGroupReq.Watch
	8,  // 8: sgroups.v1.SGroupsNetworksAPI.Upsert:input_type -> sgroups.v1.NetworkReq.Upsert
	9,  // 9: sgroups.v1.SGroupsNetworksAPI.Delete:input_type -> sgroups.v1.NetworkReq.Delete
	10, // 10: sgroups.v1.SGroupsNetworksAPI.List:input_type -> sgroups.v1.NetworkReq.List
	11, // 11: sgroups.v1.SGroupsNetworksAPI.Watch:input_type -> sgroups.v1.NetworkReq.Watch
	12, // 12: sgroups.v1.SGroupsHostsAPI.Upsert:input_type -> sgroups.v1.HostReq.Upsert
	13, // 13: sgroups.v1.SGroupsHostsAPI.Delete:input_type -> sgroups.v1.HostReq.Delete
	14, // 14: sgroups.v1.SGroupsHostsAPI.List:input_type -> sgroups.v1.HostReq.List
	15, // 15: sgroups.v1.SGroupsHostsAPI.Watch:input_type -> sgroups.v1.HostReq.Watch
	16, // 16: sgroups.v1.SGroupsHostsAPI.UpdIPs:input_type -> sgroups.v1.HostReq.UpdIPs
	17, // 17: sgroups.v1.SGroupsHostsAPI.UpdMetaInfo:input_type -> sgroups.v1.HostReq.UpdMetaInfo
	18, // 18: sgroups.v1.SGroupsHostBindingAPI.Upsert:input_type -> sgroups.v1.HostBindingReq.Upsert
	19, // 19: sgroups.v1.SGroupsHostBindingAPI.Delete:input_type -> sgroups.v1.HostBindingReq.Delete
	20, // 20: sgroups.v1.SGroupsHostBindingAPI.List:input_type -> sgroups.v1.HostBindingReq.List
	21, // 21: sgroups.v1.SGroupsHostBindingAPI.Watch:input_type -> sgroups.v1.HostBindingReq.Watch
	22, // 22: sgroups.v1.SGroupsNetworkBindingAPI.Upsert:input_type -> sgroups.v1.NetworkBindingReq.Upsert
	23, // 23: sgroups.v1.SGroupsNetworkBindingAPI.Delete:input_type -> sgroups.v1.NetworkBindingReq.Delete
	24, // 24: sgroups.v1.SGroupsNetworkBindingAPI.List:input_type -> sgroups.v1.NetworkBindingReq.List
	25, // 25: sgroups.v1.SGroupsNetworkBindingAPI.Watch:input_type -> sgroups.v1.NetworkBindingReq.Watch
	26, // 26: sgroups.v1.SGroupsRulesAPI.Upsert:input_type -> sgroups.v1.RuleReq.Upsert
	27, // 27: sgroups.v1.SGroupsRulesAPI.Delete:input_type -> sgroups.v1.RuleReq.Delete
	28, // 28: sgroups.v1.SGroupsRulesAPI.List:input_type -> sgroups.v1.RuleReq.List
	29, // 29: sgroups.v1.SGroupsRulesAPI.Watch:input_type -> sgroups.v1.RuleReq.Watch
	30, // 30: sgroups.v1.SGroupsNamespaceAPI.Upsert:output_type -> sgroups.v1.NamespaceResp.Upsert
	31, // 31: sgroups.v1.SGroupsNamespaceAPI.Delete:output_type -> google.protobuf.Empty
	32, // 32: sgroups.v1.SGroupsNamespaceAPI.List:output_type -> sgroups.v1.NamespaceResp.List
	33, // 33: sgroups.v1.SGroupsNamespaceAPI.Watch:output_type -> sgroups.v1.NamespaceResp.Watch
	34, // 34: sgroups.v1.SGroupsAddressGroupsAPI.Upsert:output_type -> sgroups.v1.AddressGroupResp.Upsert
	31, // 35: sgroups.v1.SGroupsAddressGroupsAPI.Delete:output_type -> google.protobuf.Empty
	35, // 36: sgroups.v1.SGroupsAddressGroupsAPI.List:output_type -> sgroups.v1.AddressGroupResp.List
	36, // 37: sgroups.v1.SGroupsAddressGroupsAPI.Watch:output_type -> sgroups.v1.AddressGroupResp.Watch
	37, // 38: sgroups.v1.SGroupsNetworksAPI.Upsert:output_type -> sgroups.v1.NetworkResp.Upsert
	31, // 39: sgroups.v1.SGroupsNetworksAPI.Delete:output_type -> google.protobuf.Empty
	38, // 40: sgroups.v1.SGroupsNetworksAPI.List:output_type -> sgroups.v1.NetworkResp.List
	39, // 41: sgroups.v1.SGroupsNetworksAPI.Watch:output_type -> sgroups.v1.NetworkResp.Watch
	40, // 42: sgroups.v1.SGroupsHostsAPI.Upsert:output_type -> sgroups.v1.HostResp.Upsert
	31, // 43: sgroups.v1.SGroupsHostsAPI.Delete:output_type -> google.protobuf.Empty
	41, // 44: sgroups.v1.SGroupsHostsAPI.List:output_type -> sgroups.v1.HostResp.List
	42, // 45: sgroups.v1.SGroupsHostsAPI.Watch:output_type -> sgroups.v1.HostResp.Watch
	43, // 46: sgroups.v1.SGroupsHostsAPI.UpdIPs:output_type -> sgroups.v1.HostResp.UpdIPs
	44, // 47: sgroups.v1.SGroupsHostsAPI.UpdMetaInfo:output_type -> sgroups.v1.HostResp.UpdMetaInfo
	45, // 48: sgroups.v1.SGroupsHostBindingAPI.Upsert:output_type -> sgroups.v1.HostBindingResp.Upsert
	31, // 49: sgroups.v1.SGroupsHostBindingAPI.Delete:output_type -> google.protobuf.Empty
	46, // 50: sgroups.v1.SGroupsHostBindingAPI.List:output_type -> sgroups.v1.HostBindingResp.List
	47, // 51: sgroups.v1.SGroupsHostBindingAPI.Watch:output_type -> sgroups.v1.HostBindingResp.Watch
	48, // 52: sgroups.v1.SGroupsNetworkBindingAPI.Upsert:output_type -> sgroups.v1.NetworkBindingResp.Upsert
	31, // 53: sgroups.v1.SGroupsNetworkBindingAPI.Delete:output_type -> google.protobuf.Empty
	49, // 54: sgroups.v1.SGroupsNetworkBindingAPI.List:output_type -> sgroups.v1.NetworkBindingResp.List
	50, // 55: sgroups.v1.SGroupsNetworkBindingAPI.Watch:output_type -> sgroups.v1.NetworkBindingResp.Watch
	51, // 56: sgroups.v1.SGroupsRulesAPI.Upsert:output_type -> sgroups.v1.RuleResp.Upsert
	31, // 57: sgroups.v1.SGroupsRulesAPI.Delete:output_type -> google.protobuf.Empty
	52, // 58: sgroups.v1.SGroupsRulesAPI.List:output_type -> sgroups.v1.RuleResp.List
	53, // 59: sgroups.v1.SGroupsRulesAPI.Watch:output_type -> sgroups.v1.RuleResp.Watch
	30, // [30:60] is the sub-list for method output_type
	0,  // [0:30] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_sgroups_v1_services_proto_init() }
func file_sgroups_v1_services_proto_init() {
	if File_sgroups_v1_services_proto != nil {
		return
	}
	file_sgroups_v1_queries_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgroups_v1_services_proto_rawDesc), len(file_sgroups_v1_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_sgroups_v1_services_proto_goTypes,
		DependencyIndexes: file_sgroups_v1_services_proto_depIdxs,
	}.Build()
	File_sgroups_v1_services_proto = out.File
	file_sgroups_v1_services_proto_goTypes = nil
	file_sgroups_v1_services_proto_depIdxs = nil
}
