// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: sgroups/v1/services.proto

package sgroupsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SGroupsNamespaceAPI_Upsert_FullMethodName = "/sgroups.v1.SGroupsNamespaceAPI/Upsert"
	SGroupsNamespaceAPI_Delete_FullMethodName = "/sgroups.v1.SGroupsNamespaceAPI/Delete"
	SGroupsNamespaceAPI_List_FullMethodName   = "/sgroups.v1.SGroupsNamespaceAPI/List"
	SGroupsNamespaceAPI_Watch_FullMethodName  = "/sgroups.v1.SGroupsNamespaceAPI/Watch"
)

// SGroupsNamespaceAPIClient is the client API for SGroupsNamespaceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsNamespaceAPI: SGroups namespaces API
type SGroupsNamespaceAPIClient interface {
	// Upsert: Create or update namespace(es)
	Upsert(ctx context.Context, in *NamespaceReq_Upsert, opts ...grpc.CallOption) (*NamespaceList, error)
	// Delete: Delete namespace(es)
	Delete(ctx context.Context, in *NamespaceReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List namespace(es)
	List(ctx context.Context, in *NamespaceReq_List, opts ...grpc.CallOption) (*NamespaceList, error)
	// Watch: Watch namespace(es)
	Watch(ctx context.Context, in *NamespaceReq_Watch, opts ...grpc.CallOption) (*NamespaceList, error)
}

type sGroupsNamespaceAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsNamespaceAPIClient(cc grpc.ClientConnInterface) SGroupsNamespaceAPIClient {
	return &sGroupsNamespaceAPIClient{cc}
}

func (c *sGroupsNamespaceAPIClient) Upsert(ctx context.Context, in *NamespaceReq_Upsert, opts ...grpc.CallOption) (*NamespaceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceList)
	err := c.cc.Invoke(ctx, SGroupsNamespaceAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNamespaceAPIClient) Delete(ctx context.Context, in *NamespaceReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsNamespaceAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNamespaceAPIClient) List(ctx context.Context, in *NamespaceReq_List, opts ...grpc.CallOption) (*NamespaceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceList)
	err := c.cc.Invoke(ctx, SGroupsNamespaceAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNamespaceAPIClient) Watch(ctx context.Context, in *NamespaceReq_Watch, opts ...grpc.CallOption) (*NamespaceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceList)
	err := c.cc.Invoke(ctx, SGroupsNamespaceAPI_Watch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SGroupsNamespaceAPIServer is the server API for SGroupsNamespaceAPI service.
// All implementations must embed UnimplementedSGroupsNamespaceAPIServer
// for forward compatibility.
//
// SGroupsNamespaceAPI: SGroups namespaces API
type SGroupsNamespaceAPIServer interface {
	// Upsert: Create or update namespace(es)
	Upsert(context.Context, *NamespaceReq_Upsert) (*NamespaceList, error)
	// Delete: Delete namespace(es)
	Delete(context.Context, *NamespaceReq_Delete) (*emptypb.Empty, error)
	// List: List namespace(es)
	List(context.Context, *NamespaceReq_List) (*NamespaceList, error)
	// Watch: Watch namespace(es)
	Watch(context.Context, *NamespaceReq_Watch) (*NamespaceList, error)
	mustEmbedUnimplementedSGroupsNamespaceAPIServer()
}

// UnimplementedSGroupsNamespaceAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsNamespaceAPIServer struct{}

func (UnimplementedSGroupsNamespaceAPIServer) Upsert(context.Context, *NamespaceReq_Upsert) (*NamespaceList, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsNamespaceAPIServer) Delete(context.Context, *NamespaceReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsNamespaceAPIServer) List(context.Context, *NamespaceReq_List) (*NamespaceList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsNamespaceAPIServer) Watch(context.Context, *NamespaceReq_Watch) (*NamespaceList, error) {
	return nil, status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsNamespaceAPIServer) mustEmbedUnimplementedSGroupsNamespaceAPIServer() {}
func (UnimplementedSGroupsNamespaceAPIServer) testEmbeddedByValue()                             {}

// UnsafeSGroupsNamespaceAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsNamespaceAPIServer will
// result in compilation errors.
type UnsafeSGroupsNamespaceAPIServer interface {
	mustEmbedUnimplementedSGroupsNamespaceAPIServer()
}

func RegisterSGroupsNamespaceAPIServer(s grpc.ServiceRegistrar, srv SGroupsNamespaceAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsNamespaceAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsNamespaceAPI_ServiceDesc, srv)
}

func _SGroupsNamespaceAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNamespaceAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNamespaceAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNamespaceAPIServer).Upsert(ctx, req.(*NamespaceReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNamespaceAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNamespaceAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNamespaceAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNamespaceAPIServer).Delete(ctx, req.(*NamespaceReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNamespaceAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNamespaceAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNamespaceAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNamespaceAPIServer).List(ctx, req.(*NamespaceReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNamespaceAPI_Watch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceReq_Watch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNamespaceAPIServer).Watch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNamespaceAPI_Watch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNamespaceAPIServer).Watch(ctx, req.(*NamespaceReq_Watch))
	}
	return interceptor(ctx, in, info, handler)
}

// SGroupsNamespaceAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsNamespaceAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsNamespaceAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsNamespaceAPI",
	HandlerType: (*SGroupsNamespaceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsNamespaceAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsNamespaceAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsNamespaceAPI_List_Handler,
		},
		{
			MethodName: "Watch",
			Handler:    _SGroupsNamespaceAPI_Watch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sgroups/v1/services.proto",
}

const (
	SGroupsAddressGroupsAPI_Upsert_FullMethodName = "/sgroups.v1.SGroupsAddressGroupsAPI/Upsert"
	SGroupsAddressGroupsAPI_Delete_FullMethodName = "/sgroups.v1.SGroupsAddressGroupsAPI/Delete"
	SGroupsAddressGroupsAPI_List_FullMethodName   = "/sgroups.v1.SGroupsAddressGroupsAPI/List"
	SGroupsAddressGroupsAPI_Watch_FullMethodName  = "/sgroups.v1.SGroupsAddressGroupsAPI/Watch"
)

// SGroupsAddressGroupsAPIClient is the client API for SGroupsAddressGroupsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsAddressGroupsAPI: SGroups AddressGroups API
type SGroupsAddressGroupsAPIClient interface {
	// Upsert: Create or update address group(s)
	Upsert(ctx context.Context, in *AddressGroupReq_Upsert, opts ...grpc.CallOption) (*AddressGroupList, error)
	// Delete: Delete address group(s)
	Delete(ctx context.Context, in *AddressGroupReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List address group(s)
	List(ctx context.Context, in *AddressGroupReq_List, opts ...grpc.CallOption) (*AddressGroupList, error)
	// Watch: Watch address group(s)
	Watch(ctx context.Context, in *AddressGroupReq_Watch, opts ...grpc.CallOption) (*AddressGroupList, error)
}

type sGroupsAddressGroupsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsAddressGroupsAPIClient(cc grpc.ClientConnInterface) SGroupsAddressGroupsAPIClient {
	return &sGroupsAddressGroupsAPIClient{cc}
}

func (c *sGroupsAddressGroupsAPIClient) Upsert(ctx context.Context, in *AddressGroupReq_Upsert, opts ...grpc.CallOption) (*AddressGroupList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressGroupList)
	err := c.cc.Invoke(ctx, SGroupsAddressGroupsAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsAddressGroupsAPIClient) Delete(ctx context.Context, in *AddressGroupReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsAddressGroupsAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsAddressGroupsAPIClient) List(ctx context.Context, in *AddressGroupReq_List, opts ...grpc.CallOption) (*AddressGroupList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressGroupList)
	err := c.cc.Invoke(ctx, SGroupsAddressGroupsAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsAddressGroupsAPIClient) Watch(ctx context.Context, in *AddressGroupReq_Watch, opts ...grpc.CallOption) (*AddressGroupList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressGroupList)
	err := c.cc.Invoke(ctx, SGroupsAddressGroupsAPI_Watch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SGroupsAddressGroupsAPIServer is the server API for SGroupsAddressGroupsAPI service.
// All implementations must embed UnimplementedSGroupsAddressGroupsAPIServer
// for forward compatibility.
//
// SGroupsAddressGroupsAPI: SGroups AddressGroups API
type SGroupsAddressGroupsAPIServer interface {
	// Upsert: Create or update address group(s)
	Upsert(context.Context, *AddressGroupReq_Upsert) (*AddressGroupList, error)
	// Delete: Delete address group(s)
	Delete(context.Context, *AddressGroupReq_Delete) (*emptypb.Empty, error)
	// List: List address group(s)
	List(context.Context, *AddressGroupReq_List) (*AddressGroupList, error)
	// Watch: Watch address group(s)
	Watch(context.Context, *AddressGroupReq_Watch) (*AddressGroupList, error)
	mustEmbedUnimplementedSGroupsAddressGroupsAPIServer()
}

// UnimplementedSGroupsAddressGroupsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsAddressGroupsAPIServer struct{}

func (UnimplementedSGroupsAddressGroupsAPIServer) Upsert(context.Context, *AddressGroupReq_Upsert) (*AddressGroupList, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsAddressGroupsAPIServer) Delete(context.Context, *AddressGroupReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsAddressGroupsAPIServer) List(context.Context, *AddressGroupReq_List) (*AddressGroupList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsAddressGroupsAPIServer) Watch(context.Context, *AddressGroupReq_Watch) (*AddressGroupList, error) {
	return nil, status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsAddressGroupsAPIServer) mustEmbedUnimplementedSGroupsAddressGroupsAPIServer() {
}
func (UnimplementedSGroupsAddressGroupsAPIServer) testEmbeddedByValue() {}

// UnsafeSGroupsAddressGroupsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsAddressGroupsAPIServer will
// result in compilation errors.
type UnsafeSGroupsAddressGroupsAPIServer interface {
	mustEmbedUnimplementedSGroupsAddressGroupsAPIServer()
}

func RegisterSGroupsAddressGroupsAPIServer(s grpc.ServiceRegistrar, srv SGroupsAddressGroupsAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsAddressGroupsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsAddressGroupsAPI_ServiceDesc, srv)
}

func _SGroupsAddressGroupsAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressGroupReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsAddressGroupsAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsAddressGroupsAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsAddressGroupsAPIServer).Upsert(ctx, req.(*AddressGroupReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsAddressGroupsAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressGroupReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsAddressGroupsAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsAddressGroupsAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsAddressGroupsAPIServer).Delete(ctx, req.(*AddressGroupReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsAddressGroupsAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressGroupReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsAddressGroupsAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsAddressGroupsAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsAddressGroupsAPIServer).List(ctx, req.(*AddressGroupReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsAddressGroupsAPI_Watch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressGroupReq_Watch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsAddressGroupsAPIServer).Watch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsAddressGroupsAPI_Watch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsAddressGroupsAPIServer).Watch(ctx, req.(*AddressGroupReq_Watch))
	}
	return interceptor(ctx, in, info, handler)
}

// SGroupsAddressGroupsAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsAddressGroupsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsAddressGroupsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsAddressGroupsAPI",
	HandlerType: (*SGroupsAddressGroupsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsAddressGroupsAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsAddressGroupsAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsAddressGroupsAPI_List_Handler,
		},
		{
			MethodName: "Watch",
			Handler:    _SGroupsAddressGroupsAPI_Watch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sgroups/v1/services.proto",
}
