// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent/v1/domains.proto

package agentv1

import (
	common "github.com/PRO-Robotech/sgroups-proto/pkg/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConnState: represents connection state
type ConnState int32

const (
	// CONN_UNDEF: undefined connection state
	ConnState_CONN_UNDEF ConnState = 0
	// ESTABLISHED: connection is established
	ConnState_ESTABLISHED ConnState = 1
	// SYN_SENT: connection is in SYN_SENT state
	ConnState_SYN_SENT ConnState = 2
	// SYN_RECV: connection is in SYN_RECV state
	ConnState_SYN_RECV ConnState = 3
	// FIN_WAIT1: connection is in FIN_WAIT1 state
	ConnState_FIN_WAIT1 ConnState = 4
	// FIN_WAIT2: connection is in FIN_WAIT2 state
	ConnState_FIN_WAIT2 ConnState = 5
	// TIME_WAIT: connection is in TIME_WAIT state
	ConnState_TIME_WAIT ConnState = 6
	// CLOSE: connection is closed
	ConnState_CLOSE ConnState = 7
	// CLOSE_WAIT: connection is in CLOSE_WAIT state
	ConnState_CLOSE_WAIT ConnState = 8
	// LAST_ACK: connection is in LAST_ACK state
	ConnState_LAST_ACK ConnState = 9
	// LISTEN: connection is in LISTEN state
	ConnState_LISTEN ConnState = 10
	// CLOSING: connection is in CLOSING state
	ConnState_CLOSING ConnState = 11
	// NEW_SYN_RECV: connection is in NEW_SYN_RECV state
	ConnState_NEW_SYN_RECV ConnState = 12
)

// Enum value maps for ConnState.
var (
	ConnState_name = map[int32]string{
		0:  "CONN_UNDEF",
		1:  "ESTABLISHED",
		2:  "SYN_SENT",
		3:  "SYN_RECV",
		4:  "FIN_WAIT1",
		5:  "FIN_WAIT2",
		6:  "TIME_WAIT",
		7:  "CLOSE",
		8:  "CLOSE_WAIT",
		9:  "LAST_ACK",
		10: "LISTEN",
		11: "CLOSING",
		12: "NEW_SYN_RECV",
	}
	ConnState_value = map[string]int32{
		"CONN_UNDEF":   0,
		"ESTABLISHED":  1,
		"SYN_SENT":     2,
		"SYN_RECV":     3,
		"FIN_WAIT1":    4,
		"FIN_WAIT2":    5,
		"TIME_WAIT":    6,
		"CLOSE":        7,
		"CLOSE_WAIT":   8,
		"LAST_ACK":     9,
		"LISTEN":       10,
		"CLOSING":      11,
		"NEW_SYN_RECV": 12,
	}
)

func (x ConnState) Enum() *ConnState {
	p := new(ConnState)
	*p = x
	return p
}

func (x ConnState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_domains_proto_enumTypes[0].Descriptor()
}

func (ConnState) Type() protoreflect.EnumType {
	return &file_agent_v1_domains_proto_enumTypes[0]
}

func (x ConnState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnState.Descriptor instead.
func (ConnState) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_domains_proto_rawDescGZIP(), []int{0}
}

// ProcessInfo: represents process information
type ProcessInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pid: process ID
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Comm: process command name
	Comm string `protobuf:"bytes,2,opt,name=comm,proto3" json:"comm,omitempty"`
	// CmdLine: process command line
	CmdLine string `protobuf:"bytes,3,opt,name=cmd_line,json=cmdLine,proto3" json:"cmd_line,omitempty"`
	// Exe: process executable path
	Exe string `protobuf:"bytes,4,opt,name=exe,proto3" json:"exe,omitempty"`
	// Fd: process file descriptor associated with the socket
	Fd            int32 `protobuf:"varint,5,opt,name=fd,proto3" json:"fd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_agent_v1_domains_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_domains_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_domains_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ProcessInfo) GetCmdLine() string {
	if x != nil {
		return x.CmdLine
	}
	return ""
}

func (x *ProcessInfo) GetExe() string {
	if x != nil {
		return x.Exe
	}
	return ""
}

func (x *ProcessInfo) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

// SockStat: represents socket statistics
type SockStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol: socket protocol
	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Family: socket address family
	Family common.IpAddrFamily `protobuf:"varint,2,opt,name=family,proto3,enum=common.IpAddrFamily" json:"family,omitempty"`
	// State: connection state
	State ConnState `protobuf:"varint,3,opt,name=state,proto3,enum=agent.v1.ConnState" json:"state,omitempty"`
	// LocalAddr: local ip address
	LocalAddr string `protobuf:"bytes,4,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	// LocalPort: local port
	LocalPort int32 `protobuf:"varint,5,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	// RemoteAddr: remote ip address
	RemoteAddr string `protobuf:"bytes,6,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	// RemotePort: remote port
	RemotePort int32 `protobuf:"varint,7,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	// Ifname: interface name
	Ifname string `protobuf:"bytes,8,opt,name=ifname,proto3" json:"ifname,omitempty"`
	// Inode: socket inode number
	Inode int64 `protobuf:"varint,9,opt,name=inode,proto3" json:"inode,omitempty"`
	// Processes: associated processes
	Processes     []*ProcessInfo `protobuf:"bytes,10,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SockStat) Reset() {
	*x = SockStat{}
	mi := &file_agent_v1_domains_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SockStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SockStat) ProtoMessage() {}

func (x *SockStat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_domains_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SockStat.ProtoReflect.Descriptor instead.
func (*SockStat) Descriptor() ([]byte, []int) {
	return file_agent_v1_domains_proto_rawDescGZIP(), []int{1}
}

func (x *SockStat) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SockStat) GetFamily() common.IpAddrFamily {
	if x != nil {
		return x.Family
	}
	return common.IpAddrFamily(0)
}

func (x *SockStat) GetState() ConnState {
	if x != nil {
		return x.State
	}
	return ConnState_CONN_UNDEF
}

func (x *SockStat) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *SockStat) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *SockStat) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *SockStat) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *SockStat) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *SockStat) GetInode() int64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *SockStat) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

// Nftables: represents nftables information
type Nftables struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text: nftables information in text format
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Json: nftables information in json format
	Json          string `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nftables) Reset() {
	*x = Nftables{}
	mi := &file_agent_v1_domains_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nftables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nftables) ProtoMessage() {}

func (x *Nftables) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_domains_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nftables.ProtoReflect.Descriptor instead.
func (*Nftables) Descriptor() ([]byte, []int) {
	return file_agent_v1_domains_proto_rawDescGZIP(), []int{2}
}

func (x *Nftables) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Nftables) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

// Selectors: request to select socket statistics
type SockStat_Selectors struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol: socket protocol
	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Family: socket address family
	Family common.IpAddrFamily `protobuf:"varint,2,opt,name=family,proto3,enum=common.IpAddrFamily" json:"family,omitempty"`
	// State: connection state
	State ConnState `protobuf:"varint,3,opt,name=state,proto3,enum=agent.v1.ConnState" json:"state,omitempty"`
	// LocalAddr: local ip address
	LocalAddr string `protobuf:"bytes,4,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	// LocalPort: local port
	LocalPort int32 `protobuf:"varint,5,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	// RemoteAddr: remote ip address
	RemoteAddr string `protobuf:"bytes,6,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	// RemotePort: remote port
	RemotePort int32 `protobuf:"varint,7,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	// Ifname: interface name
	Ifname string `protobuf:"bytes,8,opt,name=ifname,proto3" json:"ifname,omitempty"`
	// Inode: socket inode number
	Inode int64 `protobuf:"varint,9,opt,name=inode,proto3" json:"inode,omitempty"`
	// Pid: process ID
	Pid int32 `protobuf:"varint,10,opt,name=pid,proto3" json:"pid,omitempty"`
	// Comm: process command name
	Comm          string `protobuf:"bytes,11,opt,name=comm,proto3" json:"comm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SockStat_Selectors) Reset() {
	*x = SockStat_Selectors{}
	mi := &file_agent_v1_domains_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SockStat_Selectors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SockStat_Selectors) ProtoMessage() {}

func (x *SockStat_Selectors) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_domains_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SockStat_Selectors.ProtoReflect.Descriptor instead.
func (*SockStat_Selectors) Descriptor() ([]byte, []int) {
	return file_agent_v1_domains_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SockStat_Selectors) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SockStat_Selectors) GetFamily() common.IpAddrFamily {
	if x != nil {
		return x.Family
	}
	return common.IpAddrFamily(0)
}

func (x *SockStat_Selectors) GetState() ConnState {
	if x != nil {
		return x.State
	}
	return ConnState_CONN_UNDEF
}

func (x *SockStat_Selectors) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *SockStat_Selectors) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *SockStat_Selectors) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *SockStat_Selectors) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *SockStat_Selectors) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *SockStat_Selectors) GetInode() int64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *SockStat_Selectors) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SockStat_Selectors) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

var File_agent_v1_domains_proto protoreflect.FileDescriptor

const file_agent_v1_domains_proto_rawDesc = "" +
	"\n" +
	"\x16agent/v1/domains.proto\x12\bagent.v1\x1a\x19common/ip_transport.proto\"p\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04comm\x18\x02 \x01(\tR\x04comm\x12\x19\n" +
	"\bcmd_line\x18\x03 \x01(\tR\acmdLine\x12\x10\n" +
	"\x03exe\x18\x04 \x01(\tR\x03exe\x12\x0e\n" +
	"\x02fd\x18\x05 \x01(\x05R\x02fd\"\xb9\x05\n" +
	"\bSockStat\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12,\n" +
	"\x06family\x18\x02 \x01(\x0e2\x14.common.IpAddrFamilyR\x06family\x12)\n" +
	"\x05state\x18\x03 \x01(\x0e2\x13.agent.v1.ConnStateR\x05state\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x04 \x01(\tR\tlocalAddr\x12\x1d\n" +
	"\n" +
	"local_port\x18\x05 \x01(\x05R\tlocalPort\x12\x1f\n" +
	"\vremote_addr\x18\x06 \x01(\tR\n" +
	"remoteAddr\x12\x1f\n" +
	"\vremote_port\x18\a \x01(\x05R\n" +
	"remotePort\x12\x16\n" +
	"\x06ifname\x18\b \x01(\tR\x06ifname\x12\x14\n" +
	"\x05inode\x18\t \x01(\x03R\x05inode\x123\n" +
	"\tprocesses\x18\n" +
	" \x03(\v2\x15.agent.v1.ProcessInfoR\tprocesses\x1a\xd4\x02\n" +
	"\tSelectors\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12,\n" +
	"\x06family\x18\x02 \x01(\x0e2\x14.common.IpAddrFamilyR\x06family\x12)\n" +
	"\x05state\x18\x03 \x01(\x0e2\x13.agent.v1.ConnStateR\x05state\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x04 \x01(\tR\tlocalAddr\x12\x1d\n" +
	"\n" +
	"local_port\x18\x05 \x01(\x05R\tlocalPort\x12\x1f\n" +
	"\vremote_addr\x18\x06 \x01(\tR\n" +
	"remoteAddr\x12\x1f\n" +
	"\vremote_port\x18\a \x01(\x05R\n" +
	"remotePort\x12\x16\n" +
	"\x06ifname\x18\b \x01(\tR\x06ifname\x12\x14\n" +
	"\x05inode\x18\t \x01(\x03R\x05inode\x12\x10\n" +
	"\x03pid\x18\n" +
	" \x01(\x05R\x03pid\x12\x12\n" +
	"\x04comm\x18\v \x01(\tR\x04comm\"2\n" +
	"\bNftables\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json*\xc9\x01\n" +
	"\tConnState\x12\x0e\n" +
	"\n" +
	"CONN_UNDEF\x10\x00\x12\x0f\n" +
	"\vESTABLISHED\x10\x01\x12\f\n" +
	"\bSYN_SENT\x10\x02\x12\f\n" +
	"\bSYN_RECV\x10\x03\x12\r\n" +
	"\tFIN_WAIT1\x10\x04\x12\r\n" +
	"\tFIN_WAIT2\x10\x05\x12\r\n" +
	"\tTIME_WAIT\x10\x06\x12\t\n" +
	"\x05CLOSE\x10\a\x12\x0e\n" +
	"\n" +
	"CLOSE_WAIT\x10\b\x12\f\n" +
	"\bLAST_ACK\x10\t\x12\n" +
	"\n" +
	"\x06LISTEN\x10\n" +
	"\x12\v\n" +
	"\aCLOSING\x10\v\x12\x10\n" +
	"\fNEW_SYN_RECV\x10\fB@Z>github.com/PRO-Robotech/sgroups-proto/pkg/api/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_domains_proto_rawDescOnce sync.Once
	file_agent_v1_domains_proto_rawDescData []byte
)

func file_agent_v1_domains_proto_rawDescGZIP() []byte {
	file_agent_v1_domains_proto_rawDescOnce.Do(func() {
		file_agent_v1_domains_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_domains_proto_rawDesc), len(file_agent_v1_domains_proto_rawDesc)))
	})
	return file_agent_v1_domains_proto_rawDescData
}

var file_agent_v1_domains_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_v1_domains_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agent_v1_domains_proto_goTypes = []any{
	(ConnState)(0),             // 0: agent.v1.ConnState
	(*ProcessInfo)(nil),        // 1: agent.v1.ProcessInfo
	(*SockStat)(nil),           // 2: agent.v1.SockStat
	(*Nftables)(nil),           // 3: agent.v1.Nftables
	(*SockStat_Selectors)(nil), // 4: agent.v1.SockStat.Selectors
	(common.IpAddrFamily)(0),   // 5: common.IpAddrFamily
}
var file_agent_v1_domains_proto_depIdxs = []int32{
	5, // 0: agent.v1.SockStat.family:type_name -> common.IpAddrFamily
	0, // 1: agent.v1.SockStat.state:type_name -> agent.v1.ConnState
	1, // 2: agent.v1.SockStat.processes:type_name -> agent.v1.ProcessInfo
	5, // 3: agent.v1.SockStat.Selectors.family:type_name -> common.IpAddrFamily
	0, // 4: agent.v1.SockStat.Selectors.state:type_name -> agent.v1.ConnState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_agent_v1_domains_proto_init() }
func file_agent_v1_domains_proto_init() {
	if File_agent_v1_domains_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_domains_proto_rawDesc), len(file_agent_v1_domains_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_domains_proto_goTypes,
		DependencyIndexes: file_agent_v1_domains_proto_depIdxs,
		EnumInfos:         file_agent_v1_domains_proto_enumTypes,
		MessageInfos:      file_agent_v1_domains_proto_msgTypes,
	}.Build()
	File_agent_v1_domains_proto = out.File
	file_agent_v1_domains_proto_goTypes = nil
	file_agent_v1_domains_proto_depIdxs = nil
}
