// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent/v1/services.proto

package agentv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_agent_v1_services_proto protoreflect.FileDescriptor

const file_agent_v1_services_proto_rawDesc = "" +
	"\n" +
	"\x17agent/v1/services.proto\x12\bagent.v1\x1a\x16agent/v1/queries.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xe0\x02\n" +
	"\bAgentAPI\x12\x9c\x01\n" +
	"\x14ListSocketStatistics\x12\x1c.agent.v1.SocketStatReq.List\x1a\x1d.agent.v1.SocketStatResp.List\"G\x92A.\x1a,ListSocketStatistics: List socket statistics\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/ss/list\x12\xa4\x01\n" +
	"\x15WatchSocketStatistics\x12\x1d.agent.v1.SocketStatReq.Watch\x1a\x1e.agent.v1.SocketStatResp.Watch\"J\x92A0\x1a.WatchSocketStatistics: Watch socket statistics\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/ss/watch0\x01\x1a\x0e\x92A\v\x12\tAgent APIB\xaa\x01\x92Ag\x12\x10\n" +
	"\tAgent API2\x031.0*\x01\x012\x10application/json:\x10application/jsonr,\n" +
	"\rDocumentation\x12\x1bhttps://h-bf.prorobotech.ruZ>github.com/PRO-Robotech/sgroups-proto/pkg/api/agent/v1;agentv1b\x06proto3"

var file_agent_v1_services_proto_goTypes = []any{
	(*SocketStatReq_List)(nil),   // 0: agent.v1.SocketStatReq.List
	(*SocketStatReq_Watch)(nil),  // 1: agent.v1.SocketStatReq.Watch
	(*SocketStatResp_List)(nil),  // 2: agent.v1.SocketStatResp.List
	(*SocketStatResp_Watch)(nil), // 3: agent.v1.SocketStatResp.Watch
}
var file_agent_v1_services_proto_depIdxs = []int32{
	0, // 0: agent.v1.AgentAPI.ListSocketStatistics:input_type -> agent.v1.SocketStatReq.List
	1, // 1: agent.v1.AgentAPI.WatchSocketStatistics:input_type -> agent.v1.SocketStatReq.Watch
	2, // 2: agent.v1.AgentAPI.ListSocketStatistics:output_type -> agent.v1.SocketStatResp.List
	3, // 3: agent.v1.AgentAPI.WatchSocketStatistics:output_type -> agent.v1.SocketStatResp.Watch
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_v1_services_proto_init() }
func file_agent_v1_services_proto_init() {
	if File_agent_v1_services_proto != nil {
		return
	}
	file_agent_v1_queries_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_services_proto_rawDesc), len(file_agent_v1_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_services_proto_goTypes,
		DependencyIndexes: file_agent_v1_services_proto_depIdxs,
	}.Build()
	File_agent_v1_services_proto = out.File
	file_agent_v1_services_proto_goTypes = nil
	file_agent_v1_services_proto_depIdxs = nil
}
