// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agent/v1/services.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/PRO-Robotech/sgroups-proto/pkg/api/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentAPIName is the fully-qualified name of the AgentAPI service.
	AgentAPIName = "agent.v1.AgentAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentAPIListSocketStatisticsProcedure is the fully-qualified name of the AgentAPI's
	// ListSocketStatistics RPC.
	AgentAPIListSocketStatisticsProcedure = "/agent.v1.AgentAPI/ListSocketStatistics"
	// AgentAPIWatchSocketStatisticsProcedure is the fully-qualified name of the AgentAPI's
	// WatchSocketStatistics RPC.
	AgentAPIWatchSocketStatisticsProcedure = "/agent.v1.AgentAPI/WatchSocketStatistics"
)

// AgentAPIClient is a client for the agent.v1.AgentAPI service.
type AgentAPIClient interface {
	// ListSocketStatistics: list socket statistics
	ListSocketStatistics(context.Context, *connect.Request[v1.SocketStatReq_List]) (*connect.Response[v1.SocketStatResp_List], error)
	// WatchSocketStatistics: watch socket statistics
	WatchSocketStatistics(context.Context, *connect.Request[v1.SocketStatReq_Watch]) (*connect.ServerStreamForClient[v1.SocketStatResp_Watch], error)
}

// NewAgentAPIClient constructs a client for the agent.v1.AgentAPI service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentAPIMethods := v1.File_agent_v1_services_proto.Services().ByName("AgentAPI").Methods()
	return &agentAPIClient{
		listSocketStatistics: connect.NewClient[v1.SocketStatReq_List, v1.SocketStatResp_List](
			httpClient,
			baseURL+AgentAPIListSocketStatisticsProcedure,
			connect.WithSchema(agentAPIMethods.ByName("ListSocketStatistics")),
			connect.WithClientOptions(opts...),
		),
		watchSocketStatistics: connect.NewClient[v1.SocketStatReq_Watch, v1.SocketStatResp_Watch](
			httpClient,
			baseURL+AgentAPIWatchSocketStatisticsProcedure,
			connect.WithSchema(agentAPIMethods.ByName("WatchSocketStatistics")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentAPIClient implements AgentAPIClient.
type agentAPIClient struct {
	listSocketStatistics  *connect.Client[v1.SocketStatReq_List, v1.SocketStatResp_List]
	watchSocketStatistics *connect.Client[v1.SocketStatReq_Watch, v1.SocketStatResp_Watch]
}

// ListSocketStatistics calls agent.v1.AgentAPI.ListSocketStatistics.
func (c *agentAPIClient) ListSocketStatistics(ctx context.Context, req *connect.Request[v1.SocketStatReq_List]) (*connect.Response[v1.SocketStatResp_List], error) {
	return c.listSocketStatistics.CallUnary(ctx, req)
}

// WatchSocketStatistics calls agent.v1.AgentAPI.WatchSocketStatistics.
func (c *agentAPIClient) WatchSocketStatistics(ctx context.Context, req *connect.Request[v1.SocketStatReq_Watch]) (*connect.ServerStreamForClient[v1.SocketStatResp_Watch], error) {
	return c.watchSocketStatistics.CallServerStream(ctx, req)
}

// AgentAPIHandler is an implementation of the agent.v1.AgentAPI service.
type AgentAPIHandler interface {
	// ListSocketStatistics: list socket statistics
	ListSocketStatistics(context.Context, *connect.Request[v1.SocketStatReq_List]) (*connect.Response[v1.SocketStatResp_List], error)
	// WatchSocketStatistics: watch socket statistics
	WatchSocketStatistics(context.Context, *connect.Request[v1.SocketStatReq_Watch], *connect.ServerStream[v1.SocketStatResp_Watch]) error
}

// NewAgentAPIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentAPIHandler(svc AgentAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentAPIMethods := v1.File_agent_v1_services_proto.Services().ByName("AgentAPI").Methods()
	agentAPIListSocketStatisticsHandler := connect.NewUnaryHandler(
		AgentAPIListSocketStatisticsProcedure,
		svc.ListSocketStatistics,
		connect.WithSchema(agentAPIMethods.ByName("ListSocketStatistics")),
		connect.WithHandlerOptions(opts...),
	)
	agentAPIWatchSocketStatisticsHandler := connect.NewServerStreamHandler(
		AgentAPIWatchSocketStatisticsProcedure,
		svc.WatchSocketStatistics,
		connect.WithSchema(agentAPIMethods.ByName("WatchSocketStatistics")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agent.v1.AgentAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentAPIListSocketStatisticsProcedure:
			agentAPIListSocketStatisticsHandler.ServeHTTP(w, r)
		case AgentAPIWatchSocketStatisticsProcedure:
			agentAPIWatchSocketStatisticsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentAPIHandler struct{}

func (UnimplementedAgentAPIHandler) ListSocketStatistics(context.Context, *connect.Request[v1.SocketStatReq_List]) (*connect.Response[v1.SocketStatResp_List], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.AgentAPI.ListSocketStatistics is not implemented"))
}

func (UnimplementedAgentAPIHandler) WatchSocketStatistics(context.Context, *connect.Request[v1.SocketStatReq_Watch], *connect.ServerStream[v1.SocketStatResp_Watch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.AgentAPI.WatchSocketStatistics is not implemented"))
}
