// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sgroups/v1/services.proto

package sgroupsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/PRO-Robotech/sgroups-proto/pkg/api/sgroups/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SGroupsNamespaceAPIName is the fully-qualified name of the SGroupsNamespaceAPI service.
	SGroupsNamespaceAPIName = "sgroups.v1.SGroupsNamespaceAPI"
	// SGroupsAddressGroupsAPIName is the fully-qualified name of the SGroupsAddressGroupsAPI service.
	SGroupsAddressGroupsAPIName = "sgroups.v1.SGroupsAddressGroupsAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SGroupsNamespaceAPIUpsertProcedure is the fully-qualified name of the SGroupsNamespaceAPI's
	// Upsert RPC.
	SGroupsNamespaceAPIUpsertProcedure = "/sgroups.v1.SGroupsNamespaceAPI/Upsert"
	// SGroupsNamespaceAPIDeleteProcedure is the fully-qualified name of the SGroupsNamespaceAPI's
	// Delete RPC.
	SGroupsNamespaceAPIDeleteProcedure = "/sgroups.v1.SGroupsNamespaceAPI/Delete"
	// SGroupsNamespaceAPIListProcedure is the fully-qualified name of the SGroupsNamespaceAPI's List
	// RPC.
	SGroupsNamespaceAPIListProcedure = "/sgroups.v1.SGroupsNamespaceAPI/List"
	// SGroupsNamespaceAPIWatchProcedure is the fully-qualified name of the SGroupsNamespaceAPI's Watch
	// RPC.
	SGroupsNamespaceAPIWatchProcedure = "/sgroups.v1.SGroupsNamespaceAPI/Watch"
	// SGroupsAddressGroupsAPIUpsertProcedure is the fully-qualified name of the
	// SGroupsAddressGroupsAPI's Upsert RPC.
	SGroupsAddressGroupsAPIUpsertProcedure = "/sgroups.v1.SGroupsAddressGroupsAPI/Upsert"
	// SGroupsAddressGroupsAPIDeleteProcedure is the fully-qualified name of the
	// SGroupsAddressGroupsAPI's Delete RPC.
	SGroupsAddressGroupsAPIDeleteProcedure = "/sgroups.v1.SGroupsAddressGroupsAPI/Delete"
	// SGroupsAddressGroupsAPIListProcedure is the fully-qualified name of the SGroupsAddressGroupsAPI's
	// List RPC.
	SGroupsAddressGroupsAPIListProcedure = "/sgroups.v1.SGroupsAddressGroupsAPI/List"
	// SGroupsAddressGroupsAPIWatchProcedure is the fully-qualified name of the
	// SGroupsAddressGroupsAPI's Watch RPC.
	SGroupsAddressGroupsAPIWatchProcedure = "/sgroups.v1.SGroupsAddressGroupsAPI/Watch"
)

// SGroupsNamespaceAPIClient is a client for the sgroups.v1.SGroupsNamespaceAPI service.
type SGroupsNamespaceAPIClient interface {
	// Upsert: Create or update namespace(es)
	Upsert(context.Context, *connect.Request[v1.NamespaceReq_Upsert]) (*connect.Response[v1.NamespaceList], error)
	// Delete: Delete namespace(es)
	Delete(context.Context, *connect.Request[v1.NamespaceReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List namespace(es)
	List(context.Context, *connect.Request[v1.NamespaceReq_List]) (*connect.Response[v1.NamespaceList], error)
	// Watch: Watch namespace(es)
	Watch(context.Context, *connect.Request[v1.NamespaceReq_Watch]) (*connect.Response[v1.NamespaceList], error)
}

// NewSGroupsNamespaceAPIClient constructs a client for the sgroups.v1.SGroupsNamespaceAPI service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSGroupsNamespaceAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SGroupsNamespaceAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sGroupsNamespaceAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsNamespaceAPI").Methods()
	return &sGroupsNamespaceAPIClient{
		upsert: connect.NewClient[v1.NamespaceReq_Upsert, v1.NamespaceList](
			httpClient,
			baseURL+SGroupsNamespaceAPIUpsertProcedure,
			connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.NamespaceReq_Delete, emptypb.Empty](
			httpClient,
			baseURL+SGroupsNamespaceAPIDeleteProcedure,
			connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.NamespaceReq_List, v1.NamespaceList](
			httpClient,
			baseURL+SGroupsNamespaceAPIListProcedure,
			connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.NamespaceReq_Watch, v1.NamespaceList](
			httpClient,
			baseURL+SGroupsNamespaceAPIWatchProcedure,
			connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sGroupsNamespaceAPIClient implements SGroupsNamespaceAPIClient.
type sGroupsNamespaceAPIClient struct {
	upsert *connect.Client[v1.NamespaceReq_Upsert, v1.NamespaceList]
	delete *connect.Client[v1.NamespaceReq_Delete, emptypb.Empty]
	list   *connect.Client[v1.NamespaceReq_List, v1.NamespaceList]
	watch  *connect.Client[v1.NamespaceReq_Watch, v1.NamespaceList]
}

// Upsert calls sgroups.v1.SGroupsNamespaceAPI.Upsert.
func (c *sGroupsNamespaceAPIClient) Upsert(ctx context.Context, req *connect.Request[v1.NamespaceReq_Upsert]) (*connect.Response[v1.NamespaceList], error) {
	return c.upsert.CallUnary(ctx, req)
}

// Delete calls sgroups.v1.SGroupsNamespaceAPI.Delete.
func (c *sGroupsNamespaceAPIClient) Delete(ctx context.Context, req *connect.Request[v1.NamespaceReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls sgroups.v1.SGroupsNamespaceAPI.List.
func (c *sGroupsNamespaceAPIClient) List(ctx context.Context, req *connect.Request[v1.NamespaceReq_List]) (*connect.Response[v1.NamespaceList], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls sgroups.v1.SGroupsNamespaceAPI.Watch.
func (c *sGroupsNamespaceAPIClient) Watch(ctx context.Context, req *connect.Request[v1.NamespaceReq_Watch]) (*connect.Response[v1.NamespaceList], error) {
	return c.watch.CallUnary(ctx, req)
}

// SGroupsNamespaceAPIHandler is an implementation of the sgroups.v1.SGroupsNamespaceAPI service.
type SGroupsNamespaceAPIHandler interface {
	// Upsert: Create or update namespace(es)
	Upsert(context.Context, *connect.Request[v1.NamespaceReq_Upsert]) (*connect.Response[v1.NamespaceList], error)
	// Delete: Delete namespace(es)
	Delete(context.Context, *connect.Request[v1.NamespaceReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List namespace(es)
	List(context.Context, *connect.Request[v1.NamespaceReq_List]) (*connect.Response[v1.NamespaceList], error)
	// Watch: Watch namespace(es)
	Watch(context.Context, *connect.Request[v1.NamespaceReq_Watch]) (*connect.Response[v1.NamespaceList], error)
}

// NewSGroupsNamespaceAPIHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSGroupsNamespaceAPIHandler(svc SGroupsNamespaceAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sGroupsNamespaceAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsNamespaceAPI").Methods()
	sGroupsNamespaceAPIUpsertHandler := connect.NewUnaryHandler(
		SGroupsNamespaceAPIUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsNamespaceAPIDeleteHandler := connect.NewUnaryHandler(
		SGroupsNamespaceAPIDeleteProcedure,
		svc.Delete,
		connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsNamespaceAPIListHandler := connect.NewUnaryHandler(
		SGroupsNamespaceAPIListProcedure,
		svc.List,
		connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsNamespaceAPIWatchHandler := connect.NewUnaryHandler(
		SGroupsNamespaceAPIWatchProcedure,
		svc.Watch,
		connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SGroupsNamespaceAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SGroupsNamespaceAPIUpsertProcedure:
			sGroupsNamespaceAPIUpsertHandler.ServeHTTP(w, r)
		case SGroupsNamespaceAPIDeleteProcedure:
			sGroupsNamespaceAPIDeleteHandler.ServeHTTP(w, r)
		case SGroupsNamespaceAPIListProcedure:
			sGroupsNamespaceAPIListHandler.ServeHTTP(w, r)
		case SGroupsNamespaceAPIWatchProcedure:
			sGroupsNamespaceAPIWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSGroupsNamespaceAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSGroupsNamespaceAPIHandler struct{}

func (UnimplementedSGroupsNamespaceAPIHandler) Upsert(context.Context, *connect.Request[v1.NamespaceReq_Upsert]) (*connect.Response[v1.NamespaceList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNamespaceAPI.Upsert is not implemented"))
}

func (UnimplementedSGroupsNamespaceAPIHandler) Delete(context.Context, *connect.Request[v1.NamespaceReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNamespaceAPI.Delete is not implemented"))
}

func (UnimplementedSGroupsNamespaceAPIHandler) List(context.Context, *connect.Request[v1.NamespaceReq_List]) (*connect.Response[v1.NamespaceList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNamespaceAPI.List is not implemented"))
}

func (UnimplementedSGroupsNamespaceAPIHandler) Watch(context.Context, *connect.Request[v1.NamespaceReq_Watch]) (*connect.Response[v1.NamespaceList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNamespaceAPI.Watch is not implemented"))
}

// SGroupsAddressGroupsAPIClient is a client for the sgroups.v1.SGroupsAddressGroupsAPI service.
type SGroupsAddressGroupsAPIClient interface {
	// Upsert: Create or update address group(s)
	Upsert(context.Context, *connect.Request[v1.AddressGroupReq_Upsert]) (*connect.Response[v1.AddressGroupList], error)
	// Delete: Delete address group(s)
	Delete(context.Context, *connect.Request[v1.AddressGroupReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List address group(s)
	List(context.Context, *connect.Request[v1.AddressGroupReq_List]) (*connect.Response[v1.AddressGroupList], error)
	// Watch: Watch address group(s)
	Watch(context.Context, *connect.Request[v1.AddressGroupReq_Watch]) (*connect.Response[v1.AddressGroupList], error)
}

// NewSGroupsAddressGroupsAPIClient constructs a client for the sgroups.v1.SGroupsAddressGroupsAPI
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSGroupsAddressGroupsAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SGroupsAddressGroupsAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sGroupsAddressGroupsAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsAddressGroupsAPI").Methods()
	return &sGroupsAddressGroupsAPIClient{
		upsert: connect.NewClient[v1.AddressGroupReq_Upsert, v1.AddressGroupList](
			httpClient,
			baseURL+SGroupsAddressGroupsAPIUpsertProcedure,
			connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.AddressGroupReq_Delete, emptypb.Empty](
			httpClient,
			baseURL+SGroupsAddressGroupsAPIDeleteProcedure,
			connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.AddressGroupReq_List, v1.AddressGroupList](
			httpClient,
			baseURL+SGroupsAddressGroupsAPIListProcedure,
			connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.AddressGroupReq_Watch, v1.AddressGroupList](
			httpClient,
			baseURL+SGroupsAddressGroupsAPIWatchProcedure,
			connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sGroupsAddressGroupsAPIClient implements SGroupsAddressGroupsAPIClient.
type sGroupsAddressGroupsAPIClient struct {
	upsert *connect.Client[v1.AddressGroupReq_Upsert, v1.AddressGroupList]
	delete *connect.Client[v1.AddressGroupReq_Delete, emptypb.Empty]
	list   *connect.Client[v1.AddressGroupReq_List, v1.AddressGroupList]
	watch  *connect.Client[v1.AddressGroupReq_Watch, v1.AddressGroupList]
}

// Upsert calls sgroups.v1.SGroupsAddressGroupsAPI.Upsert.
func (c *sGroupsAddressGroupsAPIClient) Upsert(ctx context.Context, req *connect.Request[v1.AddressGroupReq_Upsert]) (*connect.Response[v1.AddressGroupList], error) {
	return c.upsert.CallUnary(ctx, req)
}

// Delete calls sgroups.v1.SGroupsAddressGroupsAPI.Delete.
func (c *sGroupsAddressGroupsAPIClient) Delete(ctx context.Context, req *connect.Request[v1.AddressGroupReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls sgroups.v1.SGroupsAddressGroupsAPI.List.
func (c *sGroupsAddressGroupsAPIClient) List(ctx context.Context, req *connect.Request[v1.AddressGroupReq_List]) (*connect.Response[v1.AddressGroupList], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls sgroups.v1.SGroupsAddressGroupsAPI.Watch.
func (c *sGroupsAddressGroupsAPIClient) Watch(ctx context.Context, req *connect.Request[v1.AddressGroupReq_Watch]) (*connect.Response[v1.AddressGroupList], error) {
	return c.watch.CallUnary(ctx, req)
}

// SGroupsAddressGroupsAPIHandler is an implementation of the sgroups.v1.SGroupsAddressGroupsAPI
// service.
type SGroupsAddressGroupsAPIHandler interface {
	// Upsert: Create or update address group(s)
	Upsert(context.Context, *connect.Request[v1.AddressGroupReq_Upsert]) (*connect.Response[v1.AddressGroupList], error)
	// Delete: Delete address group(s)
	Delete(context.Context, *connect.Request[v1.AddressGroupReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List address group(s)
	List(context.Context, *connect.Request[v1.AddressGroupReq_List]) (*connect.Response[v1.AddressGroupList], error)
	// Watch: Watch address group(s)
	Watch(context.Context, *connect.Request[v1.AddressGroupReq_Watch]) (*connect.Response[v1.AddressGroupList], error)
}

// NewSGroupsAddressGroupsAPIHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSGroupsAddressGroupsAPIHandler(svc SGroupsAddressGroupsAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sGroupsAddressGroupsAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsAddressGroupsAPI").Methods()
	sGroupsAddressGroupsAPIUpsertHandler := connect.NewUnaryHandler(
		SGroupsAddressGroupsAPIUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsAddressGroupsAPIDeleteHandler := connect.NewUnaryHandler(
		SGroupsAddressGroupsAPIDeleteProcedure,
		svc.Delete,
		connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsAddressGroupsAPIListHandler := connect.NewUnaryHandler(
		SGroupsAddressGroupsAPIListProcedure,
		svc.List,
		connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsAddressGroupsAPIWatchHandler := connect.NewUnaryHandler(
		SGroupsAddressGroupsAPIWatchProcedure,
		svc.Watch,
		connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SGroupsAddressGroupsAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SGroupsAddressGroupsAPIUpsertProcedure:
			sGroupsAddressGroupsAPIUpsertHandler.ServeHTTP(w, r)
		case SGroupsAddressGroupsAPIDeleteProcedure:
			sGroupsAddressGroupsAPIDeleteHandler.ServeHTTP(w, r)
		case SGroupsAddressGroupsAPIListProcedure:
			sGroupsAddressGroupsAPIListHandler.ServeHTTP(w, r)
		case SGroupsAddressGroupsAPIWatchProcedure:
			sGroupsAddressGroupsAPIWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSGroupsAddressGroupsAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSGroupsAddressGroupsAPIHandler struct{}

func (UnimplementedSGroupsAddressGroupsAPIHandler) Upsert(context.Context, *connect.Request[v1.AddressGroupReq_Upsert]) (*connect.Response[v1.AddressGroupList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsAddressGroupsAPI.Upsert is not implemented"))
}

func (UnimplementedSGroupsAddressGroupsAPIHandler) Delete(context.Context, *connect.Request[v1.AddressGroupReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsAddressGroupsAPI.Delete is not implemented"))
}

func (UnimplementedSGroupsAddressGroupsAPIHandler) List(context.Context, *connect.Request[v1.AddressGroupReq_List]) (*connect.Response[v1.AddressGroupList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsAddressGroupsAPI.List is not implemented"))
}

func (UnimplementedSGroupsAddressGroupsAPIHandler) Watch(context.Context, *connect.Request[v1.AddressGroupReq_Watch]) (*connect.Response[v1.AddressGroupList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsAddressGroupsAPI.Watch is not implemented"))
}
