// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sgroups/v1/service.proto

package sgroupsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/PRO-Robotech/sgroups-proto/pkg/api/sgroups/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SgroupsAPIName is the fully-qualified name of the SgroupsAPI service.
	SgroupsAPIName = "sgroups.v1.SgroupsAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SgroupsAPINameSpaceUpsertProcedure is the fully-qualified name of the SgroupsAPI's
	// NameSpaceUpsert RPC.
	SgroupsAPINameSpaceUpsertProcedure = "/sgroups.v1.SgroupsAPI/NameSpaceUpsert"
)

// SgroupsAPIClient is a client for the sgroups.v1.SgroupsAPI service.
type SgroupsAPIClient interface {
	// NameSpaceUpsert: Create or update tenant namespace(es)
	NameSpaceUpsert(context.Context, *connect.Request[v1.NamespaceList]) (*connect.Response[v1.NamespaceList], error)
}

// NewSgroupsAPIClient constructs a client for the sgroups.v1.SgroupsAPI service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSgroupsAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SgroupsAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sgroupsAPIMethods := v1.File_sgroups_v1_service_proto.Services().ByName("SgroupsAPI").Methods()
	return &sgroupsAPIClient{
		nameSpaceUpsert: connect.NewClient[v1.NamespaceList, v1.NamespaceList](
			httpClient,
			baseURL+SgroupsAPINameSpaceUpsertProcedure,
			connect.WithSchema(sgroupsAPIMethods.ByName("NameSpaceUpsert")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sgroupsAPIClient implements SgroupsAPIClient.
type sgroupsAPIClient struct {
	nameSpaceUpsert *connect.Client[v1.NamespaceList, v1.NamespaceList]
}

// NameSpaceUpsert calls sgroups.v1.SgroupsAPI.NameSpaceUpsert.
func (c *sgroupsAPIClient) NameSpaceUpsert(ctx context.Context, req *connect.Request[v1.NamespaceList]) (*connect.Response[v1.NamespaceList], error) {
	return c.nameSpaceUpsert.CallUnary(ctx, req)
}

// SgroupsAPIHandler is an implementation of the sgroups.v1.SgroupsAPI service.
type SgroupsAPIHandler interface {
	// NameSpaceUpsert: Create or update tenant namespace(es)
	NameSpaceUpsert(context.Context, *connect.Request[v1.NamespaceList]) (*connect.Response[v1.NamespaceList], error)
}

// NewSgroupsAPIHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSgroupsAPIHandler(svc SgroupsAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sgroupsAPIMethods := v1.File_sgroups_v1_service_proto.Services().ByName("SgroupsAPI").Methods()
	sgroupsAPINameSpaceUpsertHandler := connect.NewUnaryHandler(
		SgroupsAPINameSpaceUpsertProcedure,
		svc.NameSpaceUpsert,
		connect.WithSchema(sgroupsAPIMethods.ByName("NameSpaceUpsert")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SgroupsAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SgroupsAPINameSpaceUpsertProcedure:
			sgroupsAPINameSpaceUpsertHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSgroupsAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSgroupsAPIHandler struct{}

func (UnimplementedSgroupsAPIHandler) NameSpaceUpsert(context.Context, *connect.Request[v1.NamespaceList]) (*connect.Response[v1.NamespaceList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SgroupsAPI.NameSpaceUpsert is not implemented"))
}
